Repository nextcloud/all-in-one, pull requests merged in 2021-12, with the labels that each got.

#13 fix the initial credential screen
  php/src/Controller/DockerController.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  readme.md
Labels: 3. to review, bug, high

#17 fix docker permission issues
  Containers/mastercontainer/Dockerfile
  Containers/mastercontainer/start.sh
  Containers/mastercontainer/supervisord.conf
  Containers/watchtower/Dockerfile
  Containers/watchtower/start.sh
Labels: 3. to review

#41 Clarify borg based backup purpose
  readme.md
Labels: 2. developing, documentation

#48 improve docs
  readme.md
Labels: 4. to release, documentation, enhancement

#58 Improve nextcloud
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#59 disable http_challenge and add https:// to the url
  Containers/apache/Caddyfile
Labels: 3. to review, enhancement

#60 exclude the session and certs folder from restore
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, enhancement

#61 remove the username for the aio interface
  php/src/Auth/AuthManager.php
  php/src/Controller/LoginController.php
  php/src/Data/ConfigurationManager.php
  php/templates/login.twig
  php/templates/setup.twig
Labels: 3. to review, enhancement

#77 upgrade buster images to bullseye
  Containers/mastercontainer/Dockerfile
  Containers/postgresql/Dockerfile
  Containers/redis/Dockerfile
Labels: 3. to review, enhancement

#63 run image prune and volume prune regularly
  Containers/mastercontainer/Dockerfile
  Containers/mastercontainer/cron.sh
Labels: 3. to review, enhancement

#64 skip any update procedure if nextcloud was just restored or backup failed or database export failed
  Containers/borgbackup/backupscript.sh
  Containers/borgbackup/start.sh
  Containers/nextcloud/entrypoint.sh
  Containers/postgresql/start.sh
Labels: 3. to review, enhancement

#62 also show failed backup if the initial backup has failed
  php/templates/containers.twig
Labels: 3. to review, enhancement

#83 add some docs about manual access to Nextcloud files/folders
  readme.md
Labels: enhancement

#84 document the way to move your files to a separate drive
  readme.md
Labels: enhancement

#85 add some documentation on how to migrate from another nextcloud installation
  migration.md
  readme.md
Labels: documentation, enhancement

#86 add a missing detail regarding migration
  migration.md
Labels: documentation, enhancement

#89 fix automatic login button url for port 8080
  Containers/mastercontainer/mastercontainer.conf
Labels: bug, high

#91 customize php-fpm config
  Containers/nextcloud/Dockerfile
Labels: 3. to review, enhancement, performance

#92 fix the restore process
  Containers/borgbackup/backupscript.sh
Labels: bug, borg
