Repository nextcloud/all-in-one, pull requests merged in 2022-07, with the labels that each got.

#873 allow to skip the domain validation and add documentation for cloud…
  php/public/index.php
  php/src/Data/ConfigurationManager.php
  php/templates/containers.twig
  readme.md
  reverse-proxy.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, documentation, enhancement

#793 allow to adjust the talk port
  Containers/mastercontainer/start.sh
  Containers/nextcloud/entrypoint.sh
  Containers/talk/Dockerfile
  Containers/talk/start.sh
  docker-compose.yml
  manual-install/update-yaml.sh
  php/containers.json
  php/public/index.php
  php/src/ContainerDefinitionFetcher.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#865 allow to set collabora dictionaries
  manual-install/update-yaml.sh
  php/containers.json
  php/public/index.php
  php/src/Controller/ConfigurationController.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
  tests/QA/050-optional-addons.md
Labels: 3. to review, enhancement

#896 fixed typo in backup section of README
  readme.md
Labels: documentation

#935 add docs on fail2ban config
  readme.md
Labels: 3. to review, documentation

#939 document how to run it with Portainer
  readme.md
Labels: 3. to review, documentation

#938 document how to change the domain
  readme.md
Labels: 3. to review, documentation

#899 document how to enable ipv6 support
  docker-rootless.md
  readme.md
Labels: 3. to review, documentation

#941 Improve docs for Cloudflare Tunnel setup
  reverse-proxy.md
Labels: 3. to review, documentation

#904 allow to specify an apache ip-binding
  Containers/mastercontainer/start.sh
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement, pending documentation

#897 only update apps on saturdays
  Containers/nextcloud/entrypoint.sh
  manual-install/update-yaml.sh
  php/templates/containers.twig
Labels: 3. to review, enhancement

#898 enable ipv6 for lighttpd
  Containers/domaincheck/lighttpd.conf
Labels: 3. to review, enhancement

#908 allow to run daily backups without automatic updates
  Containers/mastercontainer/Dockerfile
  Containers/mastercontainer/backup-time-file-watcher.sh
  Containers/mastercontainer/cron.sh
  Containers/mastercontainer/daily-backup.sh
  Containers/nextcloud/entrypoint.sh
  manual-install/update-yaml.sh
  php/containers.json
  php/public/index.php
  php/src/Controller/ConfigurationController.php
  php/src/Controller/DockerController.php
  php/src/Cron/CreateBackup.php
  php/src/Cron/StartAndUpdateContainers.php
  php/src/Cron/StartContainers.php
  php/src/Cron/StopContainers.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
Labels: 3. to review, enhancement, borg

#887 Document how to restrict the apache_port only listen on localhost
  docker-compose.yml
  reverse-proxy.md
Labels: 3. to review, documentation

#909 add documentation for running from an external script
  readme.md
  tests/QA/070-timezone-change.md
  tests/QA/080-daily-backup-script.md
Labels: 3. to review, documentation

#949 document how to run it locally
  local-instance.md
  readme.md
Labels: 3. to review, documentation

#947 add documentation on how use ACME DNS-challenge for AIO
  readme.md
  reverse-proxy.md
Labels: 3. to review, documentation

#946 add documentation for mail server
  readme.md
Labels: 3. to review, documentation

#940 add documentation on how to run multiple AIO instances on the same server
  docker-rootless.md
  multiple-instances.md
  readme.md
Labels: 3. to review, documentation

#970 fix database import for cases where the owner is not one of the expec…
  Containers/postgresql/start.sh
Labels: 3. to review, bug

#969 update clamav to 0.105.0
  Containers/clamav/Dockerfile
Labels: 3. to review, dependencies

#958 update php:fpm-alpine to 3.16
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies

#840 update Nextcloud to 24
  Containers/nextcloud/Dockerfile
  app/appinfo/info.xml
Labels: 3. to review, enhancement

#945 allow to disable the backup section
  docker-compose.yml
  php/public/index.php
  php/src/Data/ConfigurationManager.php
  php/templates/containers.twig
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#980 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review
