Repository nextcloud/all-in-one, pull requests merged in 2022-10, with the labels that each got.

#1203 fix talk startup logs
  Containers/talk/start.sh
  Containers/talk/supervisord.conf
Labels: 3. to review, bug

#1229 add channel advice
  php/templates/containers.twig
Labels: 3. to review, enhancement

#1232 use netcat for healthchecks
  Containers/apache/healthcheck.sh
  Containers/collabora/Dockerfile
  Containers/domaincheck/Dockerfile
  Containers/imaginary/Dockerfile
  Containers/nextcloud/Dockerfile
  Containers/talk/Dockerfile
Labels: 3. to review, enhancement

#1231 add a check for free space
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, enhancement

#1206 add Synology Reverse Proxyy to reverse proxy documentation
  reverse-proxy.md
Labels: 3. to review, documentation

#1235 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#1236 rework the apache reverse proxy documentation
  reverse-proxy.md
Labels: 3. to review, documentation

#1250 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#1266 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#1259 Update nginx section of reverse-proxy.md
  reverse-proxy.md
Labels: 3. to review, documentation

#1275 add 2nd tab warning
  php/public/second-tab-warning.js
  php/templates/containers.twig
Labels: 3. to review, enhancement

#1305 install borg from backports in the future
  Containers/borgbackup/Dockerfile
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, enhancement, borg

#1324 Hint about custom datadirectory path in database migration
  migration.md
Labels: 4. to release, documentation

#1325 prettify json and unescape slashes
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, enhancement

#1274 rework session deduplication
  Containers/borgbackup/backupscript.sh
  Containers/mastercontainer/session-deduplicator.sh
  php/src/Auth/AuthManager.php
  php/src/Controller/DockerController.php
  php/src/Controller/LoginController.php
  php/src/Data/DataConst.php
  php/src/Middleware/AuthMiddleware.php
Labels: 3. to review, enhancement

#1249 change entrypoint of nextcloud container to root
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/entrypoint.sh
  Containers/nextcloud/notify.sh
  Containers/nextcloud/start.sh
  docker-rootless.md
  migration.md
  readme.md
Labels: 3. to review, enhancement

#1313 rework NGINX reverse proxy docs to support CODE
  reverse-proxy.md
Labels: documentation

#1307 use the add commands to add talk settings
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#1332 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#1331 improve nginx reverse proxy documnetation
  reverse-proxy.md
Labels: documentation

#1336 optimize nginx reverse proxy documentation
  reverse-proxy.md
Labels: documentation

#1344 Make sure that the sites are really gone
  Containers/apache/Dockerfile
  Containers/mastercontainer/Dockerfile
Labels: 3. to review

#1339 improve logging situation
  Containers/apache/nextcloud.conf
  Containers/mastercontainer/Dockerfile
  Containers/mastercontainer/mastercontainer.conf
  Containers/mastercontainer/supervisord.conf
  Containers/nextcloud/supervisord.conf
Labels: 3. to review
