Repository nextcloud/all-in-one, pull requests merged in 2022-05, with the labels that each got.

#545 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#564 add Treafik 2 to reverse proxy documentation
  reverse-proxy.md
Labels: 3. to review, documentation

#563 document all options in the docker-compose file
  docker-compose.yml
Labels: 3. to review, documentation

#574 improve the reverse proxy documentation
  readme.md
  reverse-proxy.md
Labels: 3. to review, documentation

#562 document the update policy
  readme.md
Labels: 3. to review, documentation

#566 increase forms error timeout
  php/public/forms.js
Labels: 3. to review, enhancement

#573 allow volume directories for synology
  Containers/mastercontainer/start.sh
  php/templates/containers.twig
  readme.md
Labels: 3. to review, enhancement

#589 add an example caddy conf to the docker-compose file
  docker-compose.yml
  reverse-proxy.md
Labels: 3. to review, documentation

#592 improve the traefik reverse proxy documentation
  reverse-proxy.md
Labels: 3. to review, documentation

#595 fix apache not starting
  Containers/apache/Dockerfile
Labels: 3. to review, bug

#593 improve the reverse-proxy documentation another time
  docker-compose.yml
  reverse-proxy.md
Labels: 3. to review, documentation

#571 check the DNS resolving on startup
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#584 refactor allowed paths
  Containers/mastercontainer/start.sh
  php/src/Data/ConfigurationManager.php
  php/templates/containers.twig
  readme.md
Labels: 3. to review, documentation, enhancement

#627 explain that it needs port 443 a bit better
  readme.md
Labels: 3. to review, documentation

#626 document that chmod is required too
  migration.md
  readme.md
Labels: 3. to review, documentation

#634 fix onlyoffice for caddy reverse proxy
  Containers/apache/Caddyfile
Labels: 3. to review, bug

#646 Corrected typos.
  readme.md
Labels: 3. to review

#642 Fix migration doc by changing PGDP_PASS to PG_PASSWORD
  migration.md
Labels: 3. to review, documentation

#647 improve migration docs
  migration.md
Labels: 3. to review, documentation

#652 fix password copy for firefox
  php/templates/containers.twig
Labels: 3. to review, bug, enhancement

#683 improve the network creation
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#682 add nginx-proxy-manager to the reverse proxy documentation
  reverse-proxy.md
Labels: 4. to release, documentation

#678 document how to reset the instance properly
  readme.md
Labels: 3. to review, documentation

#693 document how to resolve problems with firewalld
  readme.md
Labels: 3. to review, documentation

#696 Corrected typos
  readme.md
Labels: 3. to review, enhancement

#680 make the domain check more verbose and allow to debug it better
  php/public/forms.js
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, bug, enhancement

#677 set AIO_URL port to 443 if port 8000 was discovered
  php/src/Controller/DockerController.php
Labels: 3. to review, bug

#654 allow to change the timezone
  Containers/clamav/Dockerfile
  Containers/collabora/Dockerfile
  Containers/nextcloud/Dockerfile
  manual-install/update-yaml.sh
  php/containers.json
  php/public/index.php
  php/src/Controller/ConfigurationController.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#689 fix host mounts for windows
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  readme.md
Labels: 3. to review, enhancement

#700 fix windows host access correctly
  Containers/mastercontainer/start.sh
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
  readme.md
Labels: 3. to review, documentation, enhancement

#704 improve windows volume create docs
  readme.md
Labels: 3. to review, documentation

#719 move the timezone change section to a better place
  php/templates/containers.twig
  tests/QA/050-optional-addons.md
  tests/QA/060-environmental-variables.md
  tests/QA/070-timezone-change.md
Labels: 3. to review, enhancement

#713 improve the visibility of automatic updates
  php/templates/containers.twig
Labels: 3. to review, enhancement

#729 rework some workflows
  .github/workflows/json-validator.yml
  .github/workflows/lint-php.yml
  .github/workflows/psalm-analysis.yml
  .github/workflows/shellcheck.yml
  .github/workflows/spellcheck.yml
  php/composer.json
Labels: 3. to review, enhancement

#741 it should work even if no timezone was set
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, bug, high

#720 show timezone also while container are running
  php/templates/containers.twig
Labels: 3. to review, enhancement

#728 adjust log files to be stored in a volume
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement
