Repository nextcloud/all-in-one, pull requests merged in 2022-03, with the labels that each got.

#287 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#290 add docs on how to delete backup archives manually
  readme.md
Labels: 3. to review, documentation

#291 update postgres to 14.2
  Containers/postgresql/Dockerfile
Labels: 3. to review, enhancement

#293 fix some psalm issues
  php/src/Container/ContainerVolumes.php
  php/src/Controller/DockerController.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#295 increase version to v0.6.0
  php/templates/containers.twig
Labels: 3. to review

#294 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#286 add reverse proxy docs
  readme.md
  reverse-proxy.md
Labels: 3. to review, documentation

#252 customize collabora a bit
  Containers/apache/Caddyfile
  php/containers.json
Labels: 3. to review, enhancement

#305 add docs for additional backup sync to another drive
  readme.md
Labels: 3. to review, documentation

#307 show the current channel and add links to the changelogs
  php/public/index.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#306 migrate borgbackup to alpine
  Containers/borgbackup/Dockerfile
Labels: 3. to review, enhancement

#313 don't update database container if it failed before
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#325 correctly delete sessions older than 24h
  Containers/mastercontainer/cron.sh
  php/public/index.php
Labels: 3. to review, enhancement

#331 improve domain check
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, enhancement

#328 check if the startup command was executed successfully
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#329 allow to change the password
  php/src/Controller/ConfigurationController.php
  php/src/Data/ConfigurationManager.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#330 add optional section
  php/templates/containers.twig
Labels: 3. to review, enhancement

#326 allow to change the location of Nextclouds datadir
  Containers/mastercontainer/start.sh
  Containers/nextcloud/entrypoint.sh
  php/containers.json
  php/src/ContainerDefinitionFetcher.php
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, enhancement

#332 increase version to 0.7.0
  php/templates/containers.twig
Labels: 3. to review

#334 revert migrating borg to alpine
  Containers/borgbackup/Dockerfile
Labels: 3. to review, bug

#327 add docs for changing the datadir
  readme.md
Labels: 3. to review, documentation

#335 correctly disable database update if it failed before
  php/src/Controller/DockerController.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, bug

#336 allow to get the mastercontainer logs from the frontend
  php/src/Controller/DockerController.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#343 add some sensible headings
  php/templates/containers.twig
Labels: 3. to review, enhancement

#368 Disallow creation of local external storage in some cases
  Containers/nextcloud/entrypoint.sh
  php/containers.json
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#369 get caddy and apcu correctly
  .github/workflows/dependency-updates.yml
  Containers/apache/Dockerfile
  Containers/mastercontainer/Dockerfile
Labels: 3. to review, enhancement

#371 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#352 fix domaincheck startup
  php/src/ContainerDefinitionFetcher.php
  php/src/Controller/DockerController.php
Labels: 3. to review, bug

#372 allow to check for restarting state
  php/src/Container/Container.php
  php/src/Container/State/NotRestartingState.php
  php/src/Container/State/RestartingState.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#377 move the mastercontainer section
  php/templates/containers.twig
Labels: 3. to review, enhancement

#347 move inline javascript to its own file
  php/public/automatic_reload.js
  php/templates/containers.twig
Labels: 3. to review, enhancement

#378 add clamav as option
  .github/dependabot.yml
  Containers/clamav/Dockerfile
  Containers/nextcloud/entrypoint.sh
  php/containers.json
  php/psalm-baseline.xml
  php/public/disable-clamav.js
  php/public/index.php
  php/public/options-form-submit.js
  php/src/ContainerDefinitionFetcher.php
  php/src/Controller/ConfigurationController.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
  php/templates/layout.twig
Labels: 3. to review, enhancement

#339 improve error logging in dockeractionmanager
  php/public/index.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#380 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#384 add onlyoffice and allow to disable talk and collabora
  .github/dependabot.yml
  Containers/apache/Caddyfile
  Containers/nextcloud/entrypoint.sh
  Containers/onlyoffice/Dockerfile
  php/containers.json
  php/public/disable-collabora.js
  php/public/disable-onlyoffice.js
  php/public/disable-talk.js
  php/public/index.php
  php/public/options-form-submit.js
  php/src/ContainerDefinitionFetcher.php
  php/src/Controller/ConfigurationController.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#385 add docs for macOS and improve docker testing
  Containers/mastercontainer/start.sh
  readme.md
Labels: 3. to review, documentation, enhancement

#402 adjust talk hpb config
  Containers/talk/Dockerfile
  Containers/talk/start.sh
Labels: 3. to review, enhancement

#395 add docs on how to run it on windows and improve macOS docs
  readme.md
Labels: 3. to review, enhancement

#394 clean up the AIO interface a bit
  php/templates/containers.twig
Labels: 3. to review, enhancement

#399 add support for Windows paths
  Containers/mastercontainer/start.sh
  php/src/Data/ConfigurationManager.php
  php/templates/containers.twig
  readme.md
Labels: 3. to review, enhancement

#414 update Nextcloud to 23.0.3
  Containers/nextcloud/Dockerfile
Labels: 3. to review, enhancement

#415 reorder the aio interface a bit more
  php/public/style.css
  php/templates/containers.twig
Labels: 3. to review, enhancement

#410 allow to restore the whole instance from backup
  Containers/borgbackup/backupscript.sh
  Containers/borgbackup/start.sh
  php/containers.json
  php/psalm-baseline.xml
  php/public/index.php
  php/src/Controller/ConfigurationController.php
  php/src/Controller/DockerController.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
  php/templates/setup.twig
Labels: 3. to review, enhancement, borg

#437 improve reverse proxy conf - add nginx
  reverse-proxy.md
Labels: 3. to review, documentation

#438 document how to create backup on external drive
  readme.md
Labels: 3. to review, documentation

#439 try to fix collabora
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, bug

#440 improve the restore process
  Containers/borgbackup/Dockerfile
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, bug

#442 improve showing the current status
  php/templates/containers.twig
Labels: 3. to review, enhancement

#444 update the documentation to mention reverse proxies in the first place
  readme.md
Labels: 3. to review, documentation

#445 move some stuff a bit around
  php/templates/containers.twig
Labels: 3. to review, enhancement
