Repository nextcloud/all-in-one, pull requests merged in 2022-06, with the labels that each got.

#773 Do not break the borg lock automatically
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, enhancement, borg

#759 fix the notification spam
  Containers/mastercontainer/cron.sh
Labels: 3. to review, bug

#636 allow to specify the docker socket path
  Containers/mastercontainer/start.sh
  docker-compose.yml
  php/containers.json
  php/src/ContainerDefinitionFetcher.php
  php/src/Data/ConfigurationManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#679 add apache to reverse proxy documentation
  reverse-proxy.md
Labels: 3. to review, documentation

#648 add documentation for docker rootless
  docker-compose.yml
  docker-rootless.md
  readme.md
Labels: 3. to review, documentation

#791 increase opcache buffer to 64
  Containers/nextcloud/Dockerfile
Labels: 3. to review, enhancement

#814 allow to use it even if no channel was provided
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#792 improve the ip-address check for setdomain
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, enhancement

#829 add a note on docker-rootless regarding permissions outside the conta…
  docker-rootless.md
Labels: 3. to review, documentation

#832 set the interned strings buffer to 32
  Containers/nextcloud/Dockerfile
Labels: 3. to review, enhancement

#830 fix trusted_proxies for caddy in case of a reverse proxy situation
  Containers/apache/Caddyfile
  Containers/apache/start.sh
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#795 allow to lock the backup archive for external scripts
  Containers/borgbackup/backupscript.sh
  readme.md
Labels: 3. to review, enhancement, borg

#855 docs(manual-install): Fix typo in env var
  manual-install/readme.md
Labels: 3. to review, documentation

#850 add some bruteforce documentation and some documentation on phpmyadmi…
  readme.md
Labels: 3. to review, documentation

#835 apache documentation - make the push proxy work
  reverse-proxy.md
Labels: 3. to review, documentation

#851 add docs on how to set up fail2ban
  readme.md
Labels: 3. to review, documentation

#852 document how to install Netdata
  readme.md
Labels: 3. to review, documentation

#853 add a list of requirements for integrating new containers
  readme.md
Labels: 3. to review, documentation

#864 allow to change the backup path again if the initial backup was not s…
  php/templates/containers.twig
Labels: 3. to review, enhancement, borg

#859 improve logging of setdomain and allow private ip-addresses again when running behind a reverse proxy
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, enhancement

#794 add a secret to onlyoffice
  Containers/nextcloud/entrypoint.sh
  php/containers.json
Labels: 3. to review, enhancement

#866 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#874 domain validation should be compatible with ipv6 only as well
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, bug

#875 add documentation on how to fix the internal or reserved ip-address e…
  readme.md
Labels: 3. to review, documentation
