Repository nextcloud/all-in-one, pull requests merged in 2022-12, with the labels that each got.

#1464 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#1465 Update readme.md
  readme.md
Labels: documentation

#1470 increase the loglevel for watchtower
  Containers/watchtower/start.sh
Labels: 3. to review, enhancement

#1472 add a hint what to do if the backup container was forcefully killed
  Containers/postgresql/start.sh
Labels: 3. to review, enhancement

#1473 add hint for not present appdata dir
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#1477 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#1481 re-activate error.log for php-fpm
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/supervisord.conf
Labels: 3. to review

#1363 do not delete the updater so that it can get used later on
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement, blocked

#1517 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#1514 also sync autoconfig files
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#1515 manual-install - remove container_name so that it should run using do…
  manual-install/update-yaml.sh
Labels: 3. to review, enhancement

#1516 fix spaces in env file
  manual-install/sample.conf
  manual-install/update-yaml.sh
Labels: 3. to review, enhancement

#1432 remove the apporder and twofactor_totp app
  Containers/nextcloud/entrypoint.sh
  docker-compose.yml
  manual-install/sample.conf
  manual-install/update-yaml.sh
  php/src/Data/ConfigurationManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#1513 also back up the fulltextsearch volume
  Containers/borgbackup/backupscript.sh
  php/containers.json
Labels: 3. to review, enhancement

#1496 remove pdo_mysql
  Containers/nextcloud/Dockerfile
Labels: 3. to review, enhancement

#1497 add a volume for redis
  Containers/borgbackup/backupscript.sh
  php/containers.json
Labels: 3. to review, enhancement

#1498 add a volume for collabora fonts
  php/containers.json
Labels: 3. to review, enhancement

#1495 update to Nextcloud 25
  Containers/nextcloud/Dockerfile
  app/appinfo/info.xml
Labels: 3. to review, enhancement

#1533 Don't start the Nextcloud container if the installation failed
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#1534 fix Clamav starting trap
  Containers/nextcloud/entrypoint.sh
  php/templates/containers.twig
Labels: 3. to review, enhancement

#1506 make more clear what to do when borg check fails
  php/templates/containers.twig
Labels: 3. to review, enhancement

#1539 reload in case of undefined response
  php/public/forms.js
Labels: 3. to review, enhancement

#1532 add stdbuf
  Containers/nextcloud/Dockerfile
Labels: 3. to review, enhancement

#1540 Revert "fix Clamav starting trap"
  Containers/nextcloud/entrypoint.sh
  php/templates/containers.twig
Labels: 3. to review, enhancement

#1541 change clamd startup timeout to 90s
  php/containers.json
Labels: 3. to review, enhancement

#1548 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#1544 Added cifs/smb config help to readme
  readme.md
Labels: 3. to review, documentation

#1569 add gcompat for the recognize app
  Containers/nextcloud/Dockerfile
Labels: 3. to review, enhancement

#1558 fix the turn:add syntax
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, bug

#1566 make the turnserver more reliable
  Containers/talk/Dockerfile
  Containers/talk/start.sh
Labels: 3. to review, enhancement

#1557 improve database import
  Containers/postgresql/start.sh
Labels: 3. to review, enhancement

#1499 make collabora more safe
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#1572 the files_lock app should get installed by default as well
  docker-compose.yml
  manual-install/sample.conf
  manual-install/update-yaml.sh
  php/src/Data/ConfigurationManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#1579 Revert "the files_lock app should get installed by default as well"
  docker-compose.yml
  manual-install/sample.conf
  manual-install/update-yaml.sh
  php/src/Data/ConfigurationManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#1586 manual-install: add docker profiles for optional services
  manual-install/latest-arm64.yml
  manual-install/latest.yml
  manual-install/readme.md
  manual-install/update-yaml.sh
Labels: 3. to review, enhancement

#1590 manual-install: update readme to use default docker environment file
  .gitignore
  manual-install/readme.md
Labels: 3. to review, documentation, enhancement

#1580 improve the apache reverse proxy documentation
  reverse-proxy.md
Labels: 3. to review, documentation

#1591 manual-install: add IMAGE_TAG to omit separate latest-arm64.yml
  manual-install/latest-arm64.yml
  manual-install/latest.yml
  manual-install/readme.md
  manual-install/sample.conf
  manual-install/update-yaml.sh
Labels: 3. to review, enhancement

#1595 rename values of containers definition to match docker-compose values
  manual-install/update-yaml.sh
  php/containers-schema.json
  php/containers.json
  php/psalm-baseline.xml
  php/src/Container/Container.php
  php/src/Container/ContainerInternalPorts.php
  php/src/ContainerDefinitionFetcher.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#1598 allow to hide containers from the interface via display_name
  php/containers.json
  php/templates/containers.twig
Labels: 3. to review, enhancement

#1603 substitute volume variables in dockeractionmanager
  php/src/ContainerDefinitionFetcher.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#1624 add freetype-dev and fontconfig-dev for compiliing imagick
  Containers/nextcloud/start.sh
Labels: 3. to review, bug

#1625 Revert "substitute volume variables in dockeractionmanager"
  php/src/ContainerDefinitionFetcher.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, regression

#1626 add other file types as well
  Containers/nextcloud/start.sh
Labels: 3. to review, bug

#1627 move imagick back to the dockerfile
  .github/workflows/nextcloud-update.yml
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/start.sh
Labels: 3. to review, enhancement

#1621 allow to make wrong database intialization better debuggable
  Containers/postgresql/init-user-db.sh
  Containers/postgresql/start.sh
Labels: 3. to review, enhancement

#1620 migration - add some documentation on limits regarding the database owner name
  Containers/postgresql/start.sh
  migration.md
Labels: 3. to review, documentation, enhancement

#1622 borg - add progress back and add some additional output
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, enhancement, borg

#1587 update mastercontainer to php 8.1
  .github/workflows/create-psalm-container.yml
  .github/workflows/dependency-updates.yml
  .github/workflows/lint-php.yml
  .github/workflows/php-deprecation-detector.yml
  .github/workflows/psalm-analysis.yml
  .github/workflows/psalm-update-baseline.yml
  Containers/mastercontainer/Dockerfile
  php/composer.json
  php/composer.lock
Labels: 3. to review, dependencies

#1615 improve healthcheck to only exit 1 if it is started
  Containers/apache/healthcheck.sh
  Containers/nextcloud/Dockerfile
  Containers/postgresql/Dockerfile
Labels: 3. to review, enhancement

#1619 change dockerfile links, add tzdata to fulltext, migrate healthchecks to nc
  Containers/apache/Dockerfile
  Containers/apache/healthcheck.sh
  Containers/clamav/Dockerfile
  Containers/domaincheck/Dockerfile
  Containers/fulltextsearch/Dockerfile
  Containers/imaginary/Dockerfile
  Containers/onlyoffice/Dockerfile
  Containers/postgresql/Dockerfile
Labels: 3. to review, enhancement

#1631 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#1596 secrets should only get generated if defined in secrets of container.…
  php/public/index.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#1597 allow to add container to host network
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#1637 rename volume name to source and volume location to destination
  manual-install/update-yaml.sh
  php/containers-schema.json
  php/containers.json
  php/src/ContainerDefinitionFetcher.php
Labels: 3. to review, enhancement

#1635 refactor containerports
  manual-install/update-yaml.sh
  php/containers-schema.json
  php/containers.json
  php/src/Container/ContainerPort.php
  php/src/Container/ContainerPorts.php
  php/src/ContainerDefinitionFetcher.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement
