Repository nextcloud/all-in-one, pull requests merged in 2022-08, with the labels that each got.

#991 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#1021 Grammar fix: Replace "loose" with "lose"
  manual-install/readme.md
  php/templates/containers.twig
  php/templates/setup.twig
Labels: 3. to review

#1022 Set collabora home option
  php/containers.json
Labels: 3. to review, enhancement

#1018 wait for the database startup correctly
  Containers/nextcloud/start.sh
Labels: 3. to review, enhancement

#1019 don't allow the Nextcloud container to start if the update failed
  Containers/borgbackup/backupscript.sh
  Containers/mastercontainer/daily-backup.sh
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#1024 disable onlyoffice
  php/templates/containers.twig
  readme.md
Labels: 3. to review, enhancement

#1026 add imaginary as option
  .github/dependabot.yml
  Containers/imaginary/Dockerfile
  Containers/nextcloud/entrypoint.sh
  php/containers.json
  php/public/disable-imaginary.js
  php/public/index.php
  php/public/options-form-submit.js
  php/src/ContainerDefinitionFetcher.php
  php/src/Controller/ConfigurationController.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
  readme.md
Labels: 3. to review, enhancement

#1028 allow to adjust the upload limit
  Containers/mastercontainer/start.sh
  docker-compose.yml
  manual-install/update-yaml.sh
  php/containers.json
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#1035 Set default talk port inside Dockerfile
  Containers/talk/Dockerfile
Labels: 3. to review, enhancement

#1030 allow to adjust the max upload time
  Containers/mastercontainer/start.sh
  Containers/nextcloud/Dockerfile
  docker-compose.yml
  manual-install/update-yaml.sh
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#1029 set max connections and max php children based on available hardware
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/entrypoint.sh
  Containers/postgresql/Dockerfile
  Containers/postgresql/start.sh
Labels: 3. to review, enhancement

#1052 Fix bad error message in start.sh
  Containers/talk/start.sh
Labels: 3. to review, bug

#1042 Configure tempdirectory automatically
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#1044 add fulltextsearch as option
  .github/dependabot.yml
  Containers/fulltextsearch/Dockerfile
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/activate-collabora.sh
  Containers/nextcloud/activate-fulltextsearch.sh
  Containers/nextcloud/entrypoint.sh
  Containers/nextcloud/supervisord.conf
  php/containers.json
  php/public/disable-fulltextsearch.js
  php/public/index.php
  php/public/options-form-submit.js
  php/src/ContainerDefinitionFetcher.php
  php/src/Controller/ConfigurationController.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
  readme.md
  tests/QA/050-optional-addons.md
Labels: 3. to review, enhancement

#1046 allow to back up additional directories
  Containers/borgbackup/backupscript.sh
  php/containers.json
  php/public/index.php
  php/src/Controller/ConfigurationController.php
  php/src/Data/ConfigurationManager.php
  php/src/Data/DataConst.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
  tests/QA/020-backup-and-restore.md
Labels: 3. to review, enhancement, borg

#1058 add docker healthchecks to the docker images
  Containers/apache/Dockerfile
  Containers/collabora/Dockerfile
  Containers/domaincheck/Dockerfile
  Containers/imaginary/Dockerfile
  Containers/mastercontainer/Dockerfile
  Containers/nextcloud/Dockerfile
  Containers/onlyoffice/Dockerfile
  Containers/postgresql/Dockerfile
  Containers/redis/Dockerfile
  Containers/talk/Dockerfile
Labels: 3. to review, enhancement

#1059 fix healthcheck in fulltextsearch container
  Containers/fulltextsearch/Dockerfile
Labels: 3. to review

#1060 fix apache healthcheck
  Containers/apache/Dockerfile
  Containers/apache/healthcheck.sh
Labels: 3. to review, bug

#1063 modify the docker run command to not exit if you press ctrl+c
  develop.md
  readme.md
  reverse-proxy.md
Labels: 3. to review, documentation, enhancement

#1064 use long syntax for port publishing
  develop.md
  multiple-instances.md
  readme.md
  reverse-proxy.md
Labels: 3. to review, documentation, enhancement

#1065 fix FTS
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/activate-fulltextsearch.sh
  Containers/nextcloud/entrypoint.sh
  Containers/nextcloud/supervisord.conf
Labels: 3. to review, bug
