Repository nextcloud/all-in-one, pull requests merged in 2022-04, with the labels that each got.

#451 improve instance restore for when nextcloud_datadir is set/not set
  Containers/borgbackup/backupscript.sh
  Containers/borgbackup/start.sh
Labels: 3. to review, bug, enhancement, borg

#454 fix collabora not working out of the box
  Containers/nextcloud/entrypoint.sh
  php/containers.json
Labels: 3. to review, bug

#455 add option to enable daily backups
  Containers/borgbackup/backupscript.sh
  Containers/mastercontainer/Dockerfile
  Containers/mastercontainer/backup-time-file-watcher.sh
  Containers/mastercontainer/cron.sh
  Containers/mastercontainer/supervisord.conf
  Containers/nextcloud/cron.sh
  Containers/nextcloud/entrypoint.sh
  php/containers.json
  php/public/index.php
  php/src/Controller/ConfigurationController.php
  php/src/Controller/DockerController.php
  php/src/Cron/BackupNotification.php
  php/src/Cron/DailyBackup.php
  php/src/Cron/UpdateMastercontainer.php
  php/src/Cron/UpdateNotification.php
  php/src/Data/ConfigurationManager.php
  php/src/Data/DataConst.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
Labels: 3. to review, enhancement, borg

#487 add a beta channel
  .github/workflows/spellcheck.yml
  develop.md
  php/templates/containers.twig
  php/templates/setup.twig
  readme.md
Labels: 3. to review, enhancement

#509 run caddy as different user
  Containers/mastercontainer/Dockerfile
  Containers/mastercontainer/start.sh
  Containers/mastercontainer/supervisord.conf
Labels: 3. to review, enhancement

#510 send notification for Nextcloud and app updates
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#497 refactor detection of available container updates
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, bug

#511 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#516 add qa test plans
  .github/ISSUE_TEMPLATE/Bug_report.md
  develop.md
  tests/QA/001-initial-setup.md
  tests/QA/002-new-instance.md
  tests/QA/003-automatic-login.md
  tests/QA/004-initial-backup.md
  tests/QA/010-restore-instance.md
  tests/QA/020-backup-and-restore.md
  tests/QA/030-aio-password-change.md
  tests/QA/040-login-behavior.md
  tests/QA/050-optional-addons.md
  tests/QA/assets/backup-archive/borg/.gitattributes
  tests/QA/assets/backup-archive/borg/README
  tests/QA/assets/backup-archive/borg/config
  tests/QA/assets/backup-archive/borg/data/0/1
  tests/QA/assets/backup-archive/borg/data/0/2
  tests/QA/assets/backup-archive/borg/data/0/3
  tests/QA/assets/backup-archive/borg/data/0/4
  tests/QA/assets/backup-archive/borg/hints.4
  tests/QA/assets/backup-archive/borg/index.4
  tests/QA/assets/backup-archive/borg/integrity.4
  tests/QA/assets/backup-archive/borg/nonce
  tests/QA/assets/backup-archive/readme.md
  tests/QA/readme.md
Labels: 3. to review, enhancement

#519 additional qa test plans
  tests/QA/050-optional-addons.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#520 show the initial credentials more prominent when being new
  php/templates/containers.twig
  tests/QA/002-new-instance.md
  tests/QA/004-initial-backup.md
Labels: 3. to review, enhancement

#523 improve message when docker api version is not supported
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#532 improve wording regarding daily backup
  php/src/Cron/UpdateNotification.php
  php/templates/containers.twig
  tests/QA/020-backup-and-restore.md
Labels: 3. to review, enhancement

#533 update data fingerprint when restore was done
  Containers/borgbackup/backupscript.sh
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement, borg

#534 Block Nextcloud from starting if php version is not compatible with i…
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#527 make the instance restore process better understandable
  Containers/borgbackup/backupscript.sh
  Containers/borgbackup/start.sh
  php/public/index.php
  php/src/Controller/DockerController.php
  php/src/Data/ConfigurationManager.php
  php/templates/containers.twig
  tests/QA/010-restore-instance.md
Labels: 3. to review, enhancement, borg
