Repository nextcloud/all-in-one, pull requests merged in 2022-09, with the labels that each got.

#1100 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#1113 Fix typo in mastercontainer start.sh
  Containers/mastercontainer/start.sh
Labels: 3. to review

#1116 improve healthcheck for mastercontainer
  Containers/mastercontainer/Dockerfile
  Containers/mastercontainer/healthcheck.sh
Labels: 3. to review, bug

#1129 TURN_CONF set total-quota unlimited
  Containers/talk/start.sh
Labels: 3. to review, bug

#1107 Allow to choose a different backup location if the first backup fails
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, bug

#1096 get rid of some strange lines in the mastercontainer logs
  Containers/mastercontainer/session-deduplicator.sh
Labels: 3. to review, bug

#1095 do not show progress for borg operations
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, enhancement, borg

#1092 the dbpassword and dbuser do not need to be overwritten anymore
  Containers/nextcloud/start.sh
Labels: 3. to review, bug

#1118 add a check for init-user-db.sh
  Containers/postgresql/init-user-db.sh
  Containers/postgresql/start.sh
Labels: 3. to review, enhancement

#1094 rework the daily backup script and allow to start the backup check from it
  Containers/mastercontainer/daily-backup.sh
  php/src/Controller/DockerController.php
  php/src/Cron/CheckBackup.php
  readme.md
Labels: 3. to review, enhancement, borg

#1093 fix container logs new line
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, bug

#1135 Revert "add a check for init-user-db.sh"
  Containers/postgresql/init-user-db.sh
  Containers/postgresql/start.sh
Labels: 3. to review

#1136 add a confirmation for the timezone
  php/templates/containers.twig
Labels: 3. to review, enhancement

#1097 Let the Nextcloud-Container trust custom CAs (e.g. for using LDAPS) 2
  Containers/mastercontainer/start.sh
  Containers/nextcloud/start.sh
  docker-compose.yml
  manual-install/update-yaml.sh
  php/containers.json
  php/src/ContainerDefinitionFetcher.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#1169 fix removal of the updatenotification app for migrated instances
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, bug

#1174 aio-apache configuration now uses NEXTCLOUD_HOST env variable (#1173)
  Containers/apache/nextcloud.conf
Labels: 3. to review, bug

#1177 update permissions output and fix usage of variable
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#1178 bring Apache limits in sync with PHP limits
  Containers/apache/nextcloud.conf
  manual-install/update-yaml.sh
  php/containers.json
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, bug, enhancement

#1168 small enhancements for daily-backup.sh
  Containers/mastercontainer/daily-backup.sh
  readme.md
Labels: 3. to review, enhancement

#1150 allow to disable seccomp for collabora
  docker-compose.yml
  manual-install/update-yaml.sh
  php/containers.json
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement
