Repository nextcloud/all-in-one, pull requests merged in 2022-11, with the labels that each got.

#1365 add php-deprecation-detector
  .github/workflows/php-deprecation-detector.yml
  php/composer.json
Labels: 3. to review

#1369 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#1376 Proofread and revise explanation of the initial docker run command
  readme.md
Labels: 3. to review, documentation

#1375 Add explanation of the initial docker run command to the readme
  readme.md
Labels: 3. to review, documentation

#1362 Fixed typo's readme.md
  readme.md
Labels: documentation

#1199 allow to adjust Nextcloud apps that get installed upon first startup
  Containers/mastercontainer/start.sh
  Containers/nextcloud/entrypoint.sh
  docker-compose.yml
  manual-install/update-yaml.sh
  php/containers.json
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#1381 rename TRUSTED_CACERTS_DIR to NEXTCLOUD_TRUSTED_CACERTS_DIR
  Containers/mastercontainer/start.sh
  docker-compose.yml
  manual-install/update-yaml.sh
  php/containers.json
  php/src/ContainerDefinitionFetcher.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, documentation, enhancement

#1378 improve the UX when the login is blocked
  php/templates/login.twig
Labels: 3. to review, enhancement

#1382 allow to adjust the PHP memory limit
  Containers/mastercontainer/start.sh
  docker-compose.yml
  manual-install/update-yaml.sh
  php/containers.json
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#1370 session should not get cleared automatically before 24h
  php/public/index.php
Labels: 3. to review, enhancement

#1377 allow to add dependencies and php extensions into the Nextcloud container
  .github/workflows/nextcloud-update.yml
  Containers/mastercontainer/start.sh
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/start.sh
  docker-compose.yml
  manual-install/update-yaml.sh
  php/containers.json
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#1386 follow-up to #1377
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/start.sh
  docker-compose.yml
  manual-install/update-yaml.sh
  php/src/Data/ConfigurationManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review

#1387 2nd follow-up to #1377
  Containers/mastercontainer/start.sh
  readme.md
Labels: 3. to review, enhancement

#1388 fix regex syntax
  Containers/mastercontainer/start.sh
Labels: bug

#1394 imaginary - add `-return-size` option by default
  Containers/imaginary/Dockerfile
Labels: 3. to review, enhancement

#1404 re-add the password change
  Containers/nextcloud/start.sh
Labels: 3. to review

#1419 add an AIO outdated notification
  Containers/mastercontainer/cron.sh
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/notify-all.sh
  php/src/Cron/OutdatedNotification.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#1420 make update process more stable
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#1423 add a guide on how to run automatic updates without creating a backup…
  readme.md
Labels: 3. to review, documentation

#1428 make sure to only trigger the daily-backup script if daily_backups ar…
  Containers/mastercontainer/cron.sh
Labels: 3. to review, bug

#1451 Fix reverse proxy documentation for nginx
  reverse-proxy.md
Labels: documentation
