Repository nextcloud/all-in-one, pull requests merged in 2023-04, with the labels that each got.

#2251 fix the login form
  php/public/forms.js
  php/src/Controller/LoginController.php
  php/templates/login.twig
Labels: 3. to review, bug

#2209 Note on Nextcloud 26
  Containers/nextcloud/entrypoint.sh
  manual-install/update-yaml.sh
  php/containers.json
  php/src/Controller/DockerController.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#2252 domain must contain at least one dot
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, enhancement

#2249 add a section to the readme about remote borg backups
  readme.md
Labels: 3. to review, documentation

#2256 add sysvsem
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies

#2259 define updaterdirectory and add forgotten exit
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, bug

#2255 remove temporarily added dependencies after avatar problem was fixed
  Containers/nextcloud/Dockerfile
Labels: 3. to review

#2273 add default path for borg compact
  readme.md
Labels: 3. to review, documentation

#2289 add nodejs in order to make recognize easier to install on arm64
  Containers/nextcloud/Dockerfile
Labels: 3. to review, enhancement

#2301 Talk use netcat to check stun/turn port using domain
  Containers/talk/Dockerfile
Labels: 3. to review, enhancement

#2302 apache healthcheck, check localhost apacheport with every apache port
  Containers/apache/healthcheck.sh
Labels: 3. to review, enhancement

#2307 add timeout for curl
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, enhancement

#2327 Missing brace in readme.md
  readme.md
Labels: 3. to review, documentation

#2328 talk use official coturn image
  Containers/talk/Dockerfile
Labels: 3. to review, dependencies

#2334 disabling FTS on NC26 as the migration to ES8 is still pending
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#2331 Borg - revert to default checkpoint-interval
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, enhancement

#2288 migrate imaginary container to alpine
  .github/workflows/imaginary-update.yml
  Containers/imaginary/Dockerfile
Labels: 3. to review, enhancement, dependencies

#2343 sometimes the built-in upgrader needs to run several times
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, bug

#2359 add custom ipv6 docs
  docker-ipv6-support.md
  docker-rootless.md
  readme.md
Labels: 3. to review, documentation

#2361 adjust NPM docs
  reverse-proxy.md
Labels: 3. to review, documentation

#2360 adjust RP docs
  local-instance.md
  reverse-proxy.md
Labels: 3. to review, documentation

#2362 change `-e` to long syntax `--env`
  docker-rootless.md
  readme.md
  reverse-proxy.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, documentation

#2387 add a details tag to note down more included features
  readme.md
  reverse-proxy.md
Labels: 3. to review

#2392 adut apache_max_size for helm-chart to be a string
  nextcloud-aio-helm-chart/update-helm.sh
  nextcloud-aio-helm-chart/values.yaml
Labels: 3. to review, bug

#2400 make documentation more verbose how to apply environmental variabls t…
  readme.md
  reverse-proxy.md
Labels: 3. to review, documentation

#2358 rename `DISABLE_BACKUP_SECTION` to `AIO_DISABLE_BACKUP_SECTION`
  docker-compose.yml
  php/src/Data/ConfigurationManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#2357 rename `DOCKER_SOCKET_PATH` to `WATCHTOWER_DOCKER_SOCKET_PATH`
  Containers/mastercontainer/start.sh
  docker-compose.yml
  docker-rootless.md
  multiple-instances.md
  php/containers.json
  php/src/ContainerDefinitionFetcher.php
  php/src/Data/ConfigurationManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#2376 borg - add advices how to proceed if things get wrong
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, enhancement

#2384 add a link to the performance documentation to the aio interface
  php/templates/containers.twig
Labels: 3. to review, enhancement

#2383 add a note on what to do if Nexcloud does not open
  php/templates/containers.twig
Labels: 3. to review, enhancement

#2388 rename `All In One` to `All-in-One`
  Containers/mastercontainer/start.sh
  app/appinfo/info.xml
  app/templates/admin.php
  php/templates/containers.twig
  php/templates/setup.twig
  readme.md
Labels: 3. to review, documentation, enhancement

#2385 add a note on backup retention to the AIO interface
  php/templates/containers.twig
  readme.md
Labels: 3. to review, enhancement

#2390 add a hint to manual install when people did not grant access to the …
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#2396 add further domain validation feedback
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, enhancement

#2391 add further docs on the helm-chart
  nextcloud-aio-helm-chart/readme.md
  readme.md
Labels: 3. to review, documentation

#2397 add print_red in order to make the exact mistake more discoverable
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#2389 add additional notes to the first domain input
  php/public/index.php
  php/templates/containers.twig
  readme.md
Labels: 3. to review, enhancement

#2406 mention AIO config and docs in the AIO interface
  php/public/index.php
  php/templates/containers.twig
  php/templates/includes/aio-config.twig
Labels: 3. to review, enhancement

#2413 put the aio password change into a details tag
  php/templates/containers.twig
Labels: 3. to review, enhancement

#2417 set BORG_HOST_ID to a fixed value in order to improve stale lock removal
  php/containers.json
Labels: 3. to review, enhancement, borg

#2418 put duplicated path examples into a dedicated include
  php/templates/containers.twig
  php/templates/includes/backup-dirs.twig
Labels: 3. to review, enhancement

#2422 Fix minor typo
  reverse-proxy.md
Labels: 3. to review, documentation
