Repository nextcloud/all-in-one, pull requests merged in 2023-09, with the labels that each got.

#3296 Fix a small mistake in Traefik Docs
  reverse-proxy.md
Labels: 3. to review, documentation

#3298 do not exit if TZ is set
  Containers/mastercontainer/start.sh
Labels: 3. to review, bug, high

#2986 allow to keep disabled apps
  Containers/nextcloud/entrypoint.sh
  compose.yaml
  manual-install/update-yaml.sh
  php/containers.json
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#3313 Update check - move to head request instead of get request
  php/src/Docker/DockerHubManager.php
Labels: 3. to review, enhancement

#3317 mastercontainer - limit access to php-fpm to localhost
  Containers/mastercontainer/Dockerfile
Labels: 3. to review, enhancement

#3334 Revert "nextcloud container - make /tmp a tmpfs"
  php/containers.json
Labels: 3. to review, bug, regression

#3309 rename app_ecosystem_v2 to app_api
  Containers/nextcloud/entrypoint.sh
  php/templates/containers.twig
Labels: 3. to review, enhancement

#3351 Nextcloud - update to 27.1.0
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies

#3339 typo fix
  php/templates/includes/aio-config.twig
Labels: 3. to review, enhancement

#3369 Remove backup app suggestion
  readme.md
Labels: 3. to review, documentation

#3353 Mastercontainer - use php unix socket
  Containers/mastercontainer/Dockerfile
  Containers/mastercontainer/healthcheck.sh
  Containers/mastercontainer/mastercontainer.conf
Labels: 3. to review, enhancement

#3361 clamav also uses tini internally
  php/containers.json
Labels: 3. to review, bug

#3391 Correct country code.
  readme.md
Labels: 3. to review, documentation

#3394 Revert "Mastercontainer - use php unix socket"
  Containers/mastercontainer/Dockerfile
  Containers/mastercontainer/healthcheck.sh
  Containers/mastercontainer/mastercontainer.conf
Labels: 3. to review, bug, regression

#3398 add warning to notify-push if binary was not found
  Containers/notify-push/start.sh
Labels: 3. to review, enhancement

#3417 remove justinrainbow/json-schema again
  php/composer.json
  php/composer.lock
  php/src/ContainerDefinitionFetcher.php
Labels: 3. to review, enhancement

#3414 adjust kompose script to automatically get latest version
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, dependencies

#3231 adjust docker-lint to use hadolint
  .github/workflows/docker-lint.yml
  Containers/borgbackup/Dockerfile
  Containers/clamav/Dockerfile
  Containers/collabora/Dockerfile
  Containers/docker-socket-proxy/Dockerfile
  Containers/fulltextsearch/Dockerfile
  Containers/mastercontainer/Dockerfile
  Containers/nextcloud/Dockerfile
  Containers/talk-recording/Dockerfile
  Containers/watchtower/Dockerfile
Labels: 3. to review, enhancement

#3377 drop NET_RAW from all containers
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#3314 require image_tag and add %AIO_CHANNEL% variable
  manual-install/update-yaml.sh
  php/containers-schema.json
  php/containers.json
  php/src/ContainerDefinitionFetcher.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#2637 add fail2ban as example container for testing purposes
  .github/workflows/community-containers.yml
  .github/workflows/json-validator.yml
  community-containers/fail2ban/fail2ban.json
  community-containers/fail2ban/readme.md
  community-containers/readme.md
  php/containers-schema.json
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#3318 nextcloud - limit access to php-fpm
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/entrypoint.sh
  Containers/nextcloud/start.sh
Labels: 3. to review, enhancement

#3424 allow to specify AIO_COMMUNITY_CONTAINERS
  Containers/mastercontainer/Dockerfile
  Containers/mastercontainer/start.sh
  community-containers/readme.md
  php/src/Data/ConfigurationManager.php
  php/src/Data/DataConst.php
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#3425 merge containers.json and make sure they depend on the apache container
  php/src/ContainerDefinitionFetcher.php
Labels: 3. to review, enhancement

#3429 Revert "nextcloud - limit access to php-fpm"
  Containers/nextcloud/start.sh
Labels: 3. to review, bug

#3431 add docs on the community-containers feature
  community-containers/fail2ban/readme.md
  community-containers/readme.md
  readme.md
Labels: 3. to review, documentation

#3435 improve json-schema with pattern for image
  php/containers-schema.json
Labels: 3. to review, enhancement

#3436 fix helm chart
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, bug

#3439 community-containers - add plex
  community-containers/plex/plex.json
  community-containers/plex/readme.md
  community-containers/readme.md
Labels: 3. to review, enhancement

#3426 eturnal - set blacklist_peers
  Containers/talk/Dockerfile
  Containers/talk/start.sh
Labels: 3. to review, enhancement, upstream, blocked

#3445 helm-chart - remove hostport from deployment
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, bug

#3455 community-containers - add vaultwarden
  community-containers/fail2ban/fail2ban.json
  community-containers/fail2ban/readme.md
  community-containers/plex/readme.md
  community-containers/vaultwarden/readme.md
  community-containers/vaultwarden/vaultwarden.json
Labels: 3. to review, enhancement

#3456 community-containers - add pi-hole
  community-containers/pi-hole/pi-hole.json
  community-containers/pi-hole/readme.md
Labels: 3. to review, enhancement

#3457 apache ip binding - allow ipv6
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#3416 mastercontainer - use Caddy for generating self-singed cert
  Containers/mastercontainer/Caddyfile
  Containers/mastercontainer/Dockerfile
  Containers/mastercontainer/mastercontainer.conf
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement
