Repository nextcloud/all-in-one, pull requests merged in 2023-12, with the labels that each got.

#3827 Clean up formatting and minor text adjustments to reverse-proxy.md
  reverse-proxy.md
Labels: 3. to review, documentation

#3214 nextcloud - add stop_grace_period of 600s and wait for cron to finish during that time
  Containers/nextcloud/cron.sh
  php/containers.json
Labels: 3. to review, enhancement

#3866 community containers - add stalwart
  community-containers/caddy/readme.md
  community-containers/stalwart/readme.md
  community-containers/stalwart/stalwart.json
Labels: 3. to review, enhancement

#3873 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review, dependencies

#3886 fix local connection
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#3831 disable trace method and improve apache ssl conf
  Containers/apache/nextcloud.conf
  Containers/mastercontainer/mastercontainer.conf
Labels: 3. to review, enhancement

#3843 add timeout and sleep to notify-push
  Containers/notify-push/start.sh
Labels: 3. to review, enhancement

#3844 always run exec commands
  Containers/nextcloud/run-exec-commands.sh
Labels: 3. to review, enhancement

#3887 allow to install Nc28 upon initial install
  php/src/Controller/DockerController.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#3891 helm-chart - create 7.7.2-beta release
  nextcloud-aio-helm-chart/Chart.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, bug

#3894 helm - create 7.8.1-beta
  nextcloud-aio-helm-chart/Chart.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
Labels: 3. to review, dependencies

#3907 talk-recording - pull geckodriver from community
  Containers/talk-recording/Dockerfile
Labels: 3. to review, dependencies

#3913 log normal imageName instead of encodedImageName
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#3914 open logs in new tab
  php/templates/containers.twig
Labels: 3. to review, design, enhancement

#3916 startcontainer - thow our own exception so that the message is not tr…
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#3909 Update Slogan
  php/templates/containers.twig
  php/templates/setup.twig
  readme.md
Labels: 3. to review, enhancement

#3915 use correct way to do the update to new major versions
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#3933 Remove notify-push timeout again
  Containers/notify-push/start.sh
Labels: 3. to review, bug

#3934 update Nc to 27.1.5
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies

#3924 try to improve database dump logic on container shutdown
  Containers/postgresql/start.sh
Labels: 3. to review, bug
