Repository nextcloud/all-in-one, pull requests merged in 2023-02, with the labels that each got.

#1879 imaginary - allow big images by default
  Containers/imaginary/Dockerfile
Labels: 3. to review, enhancement

#1889 also write install log to logfile
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#1887 get multiarch repodigest
  php/src/Docker/DockerHubManager.php
Labels: 3. to review, enhancement

#1890 fix daily backup running into conflict with elasticsearch
  Containers/fulltextsearch/Dockerfile
  Containers/fulltextsearch/start.sh
  php/containers.json
Labels: 3. to review, bug

#1891 fix(helm): refactor sources to a string array
  helm-chart/Chart.yaml
Labels: 3. to review, bug

#1894 fix(helm): don't mark ca certs volume as read only globally
  helm-chart/templates/nextcloud-aio-apache-deployment.yaml
  helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
Labels: 3. to review, bug

#1896 fix(helm): chown database volume for postgres
  helm-chart/templates/nextcloud-aio-database-deployment.yaml
Labels: 3. to review, bug

#1899 fix database helm permissions
  helm-chart/update-helm.sh
Labels: 3. to review

#1897 try to remove readonly from global volumes automatically
  helm-chart/update-helm.sh
Labels: 3. to review

#1909 add expose property to containers definition
  php/containers-schema.json
  php/containers.json
Labels: 3. to review, enhancement

#1893 adjust variables correctly
  helm-chart/update-helm.sh
  manual-install/update-yaml.sh
Labels: 3. to review

#1912 Helm Chart updates
  helm-chart/templates/nextcloud-aio-clamav-deployment.yaml
  helm-chart/templates/nextcloud-aio-clamav-service.yaml
  helm-chart/templates/nextcloud-aio-collabora-deployment.yaml
  helm-chart/templates/nextcloud-aio-collabora-service.yaml
  helm-chart/templates/nextcloud-aio-database-deployment.yaml
  helm-chart/templates/nextcloud-aio-database-service.yaml
  helm-chart/templates/nextcloud-aio-fulltextsearch-deployment.yaml
  helm-chart/templates/nextcloud-aio-fulltextsearch-service.yaml
  helm-chart/templates/nextcloud-aio-imaginary-deployment.yaml
  helm-chart/templates/nextcloud-aio-imaginary-service.yaml
  helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
  helm-chart/templates/nextcloud-aio-nextcloud-service.yaml
  helm-chart/templates/nextcloud-aio-onlyoffice-deployment.yaml
  helm-chart/templates/nextcloud-aio-onlyoffice-service.yaml
  helm-chart/templates/nextcloud-aio-redis-deployment.yaml
  helm-chart/templates/nextcloud-aio-redis-service.yaml
  helm-chart/update-helm.sh
Labels: 3. to review

#1915 Revert "get multiarch repodigest"
  php/src/Docker/DockerHubManager.php
Labels: 3. to review, enhancement

#1924 helm - add type: loadbalancer and remove apache_ip_binding again
  helm-chart/update-helm.sh
Labels: 3. to review

#1933 adjust reverse proxy documentation to also talk about web server
  docker-compose.yml
  manual-install/update-yaml.sh
  readme.md
  reverse-proxy.md
Labels: 3. to review, documentation

#1918 also fail the installation if appdata could not get created
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#1944 fix a few problems with new install check
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, bug

#1948 imaginary - rework some things
  Containers/nextcloud/entrypoint.sh
  php/templates/containers.twig
  readme.md
Labels: 3. to review, enhancement

#1952 update windows documentation to use paths instead of volumes
  php/templates/containers.twig
  readme.md
Labels: 3. to review, documentation, enhancement

#1957 mastercontainer - increase max children and switch to pm dynamic
  Containers/mastercontainer/Dockerfile
Labels: 3. to review, bug

#1934 helm - handle talk internal ports correctly and fix permissions for Nextcloud container
  helm-chart/templates/nextcloud-aio-apache-deployment.yaml
  helm-chart/templates/nextcloud-aio-apache-service.yaml
  helm-chart/templates/nextcloud-aio-clamav-service.yaml
  helm-chart/templates/nextcloud-aio-collabora-service.yaml
  helm-chart/templates/nextcloud-aio-database-service.yaml
  helm-chart/templates/nextcloud-aio-fulltextsearch-deployment.yaml
  helm-chart/templates/nextcloud-aio-fulltextsearch-service.yaml
  helm-chart/templates/nextcloud-aio-imaginary-service.yaml
  helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
  helm-chart/templates/nextcloud-aio-nextcloud-service.yaml
  helm-chart/templates/nextcloud-aio-onlyoffice-service.yaml
  helm-chart/templates/nextcloud-aio-redis-service.yaml
  helm-chart/templates/nextcloud-aio-talk-deployment.yaml
  helm-chart/templates/nextcloud-aio-talk-service.yaml
  helm-chart/update-helm.sh
  helm-chart/values.yaml
Labels: 3. to review, enhancement

#2000 document multiarch containers
  docker-compose.yml
  helm-chart/update-helm.sh
  helm-chart/values.yaml
  manual-install/readme.md
  manual-install/sample.conf
  manual-install/update-yaml.sh
  manual-upgrade.md
  readme.md
  reverse-proxy.md
Labels: 3. to review, documentation, enhancement

#1968 rm does not work if there are too many sessions
  Containers/mastercontainer/daily-backup.sh
Labels: 3. to review, enhancement

#1969 fix and hide a few caddy warnings
  Containers/apache/Caddyfile
  Containers/apache/start.sh
  Containers/mastercontainer/Caddyfile
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#1981 check size of config and only write back if space is sufficient
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, enhancement

#1982 also restore configuration.json even if the former restore failed
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, bug

#1990 connect containers only to custom network
  php/src/Docker/DockerActionManager.php
Labels: 2. developing, bug

#2005 add loader to login template
  php/templates/login.twig
Labels: 3. to review, enhancement

#2009 postgresql - improve database online check during the migration
  Containers/postgresql/Dockerfile
  Containers/postgresql/healthcheck.sh
  Containers/postgresql/start.sh
Labels: 3. to review, bug, high

#2018 Fix typo
  readme.md
Labels: 3. to review, documentation

#2024 Add the directive ProxyPassReverse
  reverse-proxy.md
Labels: 3. to review, documentation

#2027 rp documentation - make apache_ip_binding documentation more explicit
  reverse-proxy.md
Labels: 3. to review, documentation

#2028 adjust readme a bit
  readme.md
Labels: 3. to review, documentation

#2031 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#2039 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#2048 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#1254 Improve turn server
  Containers/talk/Dockerfile
  Containers/talk/start.sh
Labels: 3. to review, enhancement

#2011 docker-aio-config should not be a volume by default
  Containers/mastercontainer/Dockerfile
Labels: 3. to review, enhancement

#2020 also overwrite db_name to fix db migration
  Containers/nextcloud/start.sh
Labels: 3. to review, enhancement

#2032 add util-linux-misc which might be required on alpine linux
  Containers/borgbackup/Dockerfile
  Containers/mastercontainer/Dockerfile
Labels: 3. to review, bug

#2040 talk - improve a few things
  Containers/talk/start.sh
  php/containers.json
Labels: 3. to review, enhancement

#2042 add additional network option
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#2061 fix install check for primary object storage
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, bug

#2051 Cron: remove nextcloud-aio-domaincheck if stopped
  Containers/mastercontainer/cron.sh
Labels: 2. developing, enhancement

#2079 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review
