Repository nextcloud/all-in-one, pull requests merged in 2023-08, with the labels that each got.

#3115 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, dependencies

#3096 Update update-yaml.sh
  manual-install/latest.yml
  manual-install/update-yaml.sh
Labels: 3. to review

#3047 add executable bit on tmpfs for nextcloud container
  php/containers-schema.json
  php/containers.json
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#3048 make FTS read-only
  php/containers.json
Labels: 3. to review, enhancement

#3018 mastercontainer - run supervisord directly and not as cmd option
  Containers/mastercontainer/Dockerfile
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#3117 Revert "make FTS read-only"
  php/containers.json
Labels: 3. to review

#3071 include mozilla tls confs in reverse proxy guide
  reverse-proxy.md
Labels: 3. to review, documentation

#3118 update update-yaml.sh follow-up
  manual-install/latest.yml
  manual-install/update-yaml.sh
Labels: 3. to review

#3128 Use .Values in Helm templates
  nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-persistentvolumeclaim.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-clamav-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-clamav-persistentvolumeclaim.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-clamav-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-collabora-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-collabora-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-database-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-database-dump-persistentvolumeclaim.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-database-persistentvolumeclaim.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-database-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-elasticsearch-persistentvolumeclaim.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-fulltextsearch-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-fulltextsearch-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-imaginary-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-imaginary-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-namespace-namespace.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-data-persistentvolumeclaim.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-persistentvolumeclaim.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-trusted-cacerts-persistentvolumeclaim.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-notify-push-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-notify-push-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-onlyoffice-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-onlyoffice-persistentvolumeclaim.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-onlyoffice-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-redis-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-redis-persistentvolumeclaim.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-redis-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-recording-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-recording-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-service.yaml
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, bug

#3130 update Nextcloud to 27.0.2
  Containers/nextcloud/Dockerfile
  app/appinfo/info.xml
  php/templates/containers.twig
Labels: 3. to review, dependencies

#3132 Revert "https://github.com/nextcloud/all-in-one/pull/3021" partially
  Containers/nextcloud/config/postgresql.config.php
  Containers/nextcloud/entrypoint.sh
  Containers/nextcloud/start.sh
Labels: 3. to review, bug

#3133 add domain-validator
  Containers/mastercontainer/Caddyfile
  Containers/mastercontainer/supervisord.conf
  php/domain-validator.php
Labels: 3. to review, enhancement

#3141 name service in compose like container
  compose.yaml
Labels: 3. to review, enhancement

#3150 Update readme.md
  readme.md
Labels: 3. to review, documentation

#3151 Review in full, fixed some minor typos and phrases
  readme.md
Labels: 3. to review, documentation

#3139 disable logging for domain-validator.php
  Containers/mastercontainer/supervisord.conf
  php/domain-validator.php
Labels: 3. to review, enhancement

#3140 add init flag to all containers
  compose.yaml
  develop.md
  php/containers-schema.json
  php/containers.json
  php/src/Container/Container.php
  php/src/ContainerDefinitionFetcher.php
  php/src/Docker/DockerActionManager.php
  readme.md
  reverse-proxy.md
Labels: 3. to review, enhancement

#3153 add check for timezone
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#3157 make notify-push logs more explicit
  Containers/notify-push/start.sh
Labels: 3. to review, enhancement

#3171 change grep command
  Containers/mastercontainer/daily-backup.sh
Labels: 3. to review, enhancement

#3174 try to fix grep syntax for db restore
  Containers/postgresql/start.sh
Labels: 3. to review, bug

#3154 add check for unsupported environmental variables
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#3178 Update wording for FTS
  php/templates/containers.twig
Labels: 3. to review, enhancement

#2855 eturnal
  Containers/talk/Dockerfile
  Containers/talk/start.sh
  Containers/talk/supervisord.conf
  php/containers.json
Labels: 3. to review, enhancement, dependencies

#3181 fix notify-push trusted proxies
  Containers/apache/Dockerfile
  Containers/apache/start.sh
Labels: 3. to review, bug

#3187 apache - improve healtcheck
  Containers/apache/healthcheck.sh
Labels: 3. to review, enhancement

#3186 mastercontainer - improve healthcheck
  Containers/mastercontainer/healthcheck.sh
Labels: 3. to review, enhancement

#3208 ntofiy-push - improve healthcheck
  Containers/notify-push/Dockerfile
  Containers/notify-push/healthcheck.sh
Labels: 3. to review, enhancement

#3207 nextcloud - improve healthcheck
  .github/workflows/docker-lint.yml
  Containers/nextcloud/Dockerfile
Labels: 3. to review, enhancement

#3212 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review, dependencies

#3191 add image_tag to containers definition
  php/containers-schema.json
  php/src/Container/Container.php
  php/src/ContainerDefinitionFetcher.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#3217 talk - fix eternal relay-ip
  Containers/talk/Dockerfile
  Containers/talk/start.sh
Labels: 3. to review, bug

#3188 talk - improve healthcheck
  Containers/talk/Dockerfile
  Containers/talk/healthcheck.sh
Labels: 3. to review, enhancement

#3232 Fix OO
  Containers/nextcloud/run-exec-commands.sh
  php/containers.json
Labels: 3. to review, bug

#3235 add docker-socket-proxy as option
  .github/dependabot.yml
  Containers/docker-socket-proxy/Dockerfile
  Containers/docker-socket-proxy/haproxy.cfg
  Containers/nextcloud/entrypoint.sh
  manual-install/update-yaml.sh
  php/containers.json
  php/public/disable-docker-socket-proxy.js
  php/public/index.php
  php/public/options-form-submit.js
  php/src/ContainerDefinitionFetcher.php
  php/src/Controller/ConfigurationController.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#3242 improve some deails with docker-socket-proxy
  Containers/docker-socket-proxy/Dockerfile
  Containers/docker-socket-proxy/haproxy.cfg
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, bug

#3240 disable selinux for watchtower and docker-socket-proxy
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#3238 Fix spelling mistake in reverse-proxy.md
  reverse-proxy.md
Labels: 3. to review, documentation

#3245 fix securityopt label disabled
  php/src/Docker/DockerActionManager.php
  readme.md
Labels: 3. to review, enhancement

#3263 fix typo in apache's start.sh
  Containers/apache/start.sh
Labels: 3. to review, enhancement

#3264 Fix typo in readme.md
  readme.md
Labels: 3. to review, documentation

#3265 backupscript.sh: slight rewording for consistency
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, enhancement

#3273 Update reverse-proxy.md: clarified that unencrypted HTTP traffic is e…
  reverse-proxy.md
Labels: 3. to review, documentation

#3279 Fix typo in readme.md
  readme.md
Labels: 3. to review, documentation

#3277 adjust wording what to do if database export failed
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, enhancement

#3284 disable docker-socket-proxy temporarily
  php/public/disable-docker-socket-proxy.js
  php/public/options-form-submit.js
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#3243 improve docker-socket-proxy container
  Containers/docker-socket-proxy/Dockerfile
  Containers/docker-socket-proxy/haproxy.cfg
  Containers/docker-socket-proxy/healthcheck.sh
  Containers/docker-socket-proxy/start.sh
  php/containers.json
Labels: 2. developing, enhancement

#3286 add additinal rules for haproxy
  Containers/docker-socket-proxy/haproxy.cfg
Labels: 3. to review, enhancement
