Repository nextcloud/all-in-one, pull requests merged in 2023-01, with the labels that each got.

#1645 add types for missing ones and bring psalm-baseline down to zero
  php/psalm-baseline.xml
  php/public/index.php
  php/src/Controller/ConfigurationController.php
  php/src/Controller/DockerController.php
  php/src/Controller/LoginController.php
  php/src/Twig/ClassExtension.php
Labels: 3. to review, enhancement

#1656 fix exposing containers
  php/src/Container/ContainerPort.php
  php/src/ContainerDefinitionFetcher.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, bug

#1655 fix adding containers to the host network
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, bug

#1657 fix healthcheck for nextcloud and database
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/healthcheck.sh
  Containers/postgresql/Dockerfile
  Containers/postgresql/healthcheck.sh
Labels: 3. to review, bug

#1604 improve containeers schema
  manual-install/update-yaml.sh
  php/containers-schema.json
  php/containers.json
  php/src/ContainerDefinitionFetcher.php
Labels: 3. to review, enhancement

#1654 allow to enable shipped apps during startup
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#1660 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review

#1659 allow to add the /dev/dri device into the container and refactor devices
  Containers/nextcloud/start.sh
  docker-compose.yml
  manual-install/update-yaml.sh
  php/containers-schema.json
  php/containers.json
  php/src/Container/Container.php
  php/src/ContainerDefinitionFetcher.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#1663 set remote_font_config for collabora
  php/containers.json
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#1658 add twofactor_totp back as default enabled app
  docker-compose.yml
  manual-install/sample.conf
  manual-install/update-yaml.sh
  php/src/Data/ConfigurationManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, regression

#1670 allow to repair the integrity of the backup archive
  Containers/borgbackup/backupscript.sh
  Containers/borgbackup/start.sh
  php/public/index.php
  php/src/Controller/DockerController.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#1574 Create Helm-chart
  .github/workflows/update-helm.yml
  helm-chart/Chart.yaml
  helm-chart/readme.md
  helm-chart/templates/nextcloud-aio-apache-deployment.yaml
  helm-chart/templates/nextcloud-aio-apache-persistentvolumeclaim.yaml
  helm-chart/templates/nextcloud-aio-apache-service.yaml
  helm-chart/templates/nextcloud-aio-clamav-deployment.yaml
  helm-chart/templates/nextcloud-aio-clamav-persistentvolumeclaim.yaml
  helm-chart/templates/nextcloud-aio-collabora-deployment.yaml
  helm-chart/templates/nextcloud-aio-collabora-fonts-persistentvolumeclaim.yaml
  helm-chart/templates/nextcloud-aio-database-deployment.yaml
  helm-chart/templates/nextcloud-aio-database-dump-persistentvolumeclaim.yaml
  helm-chart/templates/nextcloud-aio-database-persistentvolumeclaim.yaml
  helm-chart/templates/nextcloud-aio-elasticsearch-persistentvolumeclaim.yaml
  helm-chart/templates/nextcloud-aio-fulltextsearch-deployment.yaml
  helm-chart/templates/nextcloud-aio-imaginary-deployment.yaml
  helm-chart/templates/nextcloud-aio-networkpolicy.yaml
  helm-chart/templates/nextcloud-aio-nextcloud-data-persistentvolumeclaim.yaml
  helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
  helm-chart/templates/nextcloud-aio-nextcloud-mount-persistentvolumeclaim.yaml
  helm-chart/templates/nextcloud-aio-nextcloud-persistentvolumeclaim.yaml
  helm-chart/templates/nextcloud-aio-nextcloud-trusted-cacerts-persistentvolumeclaim.yaml
  helm-chart/templates/nextcloud-aio-onlyoffice-deployment.yaml
  helm-chart/templates/nextcloud-aio-onlyoffice-persistentvolumeclaim.yaml
  helm-chart/templates/nextcloud-aio-redis-deployment.yaml
  helm-chart/templates/nextcloud-aio-redis-persistentvolumeclaim.yaml
  helm-chart/templates/nextcloud-aio-talk-deployment.yaml
  helm-chart/templates/nextcloud-aio-talk-service.yaml
  helm-chart/update-helm.sh
  helm-chart/values.yaml
Labels: 3. to review, enhancement

#1716 add note to resolver in nginx reverse proxy docs
  reverse-proxy.md
Labels: 3. to review, documentation

#1719 Fix the middleware name in the Traefik doc
  reverse-proxy.md
Labels: 3. to review, documentation

#1726 Remove the reference to an unknown middleware
  reverse-proxy.md
Labels: 3. to review, documentation

#1695 allow to make fulltextsearch:index issues easier to debug
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#1696 Add hint about Cloudflare Rocket Loader and Rename Cloudflare Argo Tu…
  local-instance.md
  readme.md
  reverse-proxy.md
Labels: 3. to review, documentation

#1706 fix to position of the log-out button
  php/public/style.css
  php/templates/containers.twig
Labels: 3. to review, enhancement

#1708 fix the apps not getting enabled on migration
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, bug

#1733 Fix the Traefik example
  reverse-proxy.md
Labels: 3. to review, documentation

#1732 redis: add hint to wiki if overcommit disabled
  Containers/redis/start.sh
Labels: 3. to review, enhancement

#1742 add an explanation of `--sig-proxy=false`
  readme.md
Labels: 3. to review, documentation

#1743 fix dependency-update workflow
  .github/workflows/dependency-updates.yml
  .github/workflows/shellcheck.yml
  php/composer.json
  php/composer.lock
Labels: 3. to review, bug, dependencies

#1741 Rewrite Traefik examples using YAML
  reverse-proxy.md
Labels: 3. to review, documentation

#1756 add a hint that NEXTCLOUD_DATADIR needs to be specified before the fi…
  readme.md
Labels: 3. to review, documentation

#1750 Add Notes on Cloudflare to readme
  readme.md
Labels: 3. to review, documentation

#1736 borg - substitute prefix with glob-archives
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, enhancement

#1585 update redis to v7
  Containers/redis/Dockerfile
Labels: 3. to review, dependencies

#1763 change instructions on how to install docker
  readme.md
Labels: 3. to review, documentation

#1764 make more verbose that reverse proxy setup is different
  readme.md
Labels: 3. to review, documentation

#1767 alpine - remove the update arg
  Containers/clamav/Dockerfile
  Containers/domaincheck/Dockerfile
  Containers/postgresql/Dockerfile
  Containers/redis/Dockerfile
  Containers/watchtower/Dockerfile
Labels: 3. to review, enhancement

#1578 migrate borgbackup container to alpine
  Containers/borgbackup/Dockerfile
Labels: 3. to review, enhancement, borg

#1769 add further note about cloudflare and domain validation
  readme.md
Labels: 3. to review, documentation

#1770 cloudflare - add note about missing hsts header
  readme.md
Labels: 3. to review, documentation

#1771 cloudflare - add note about possible problems with cert issuing
  readme.md
Labels: 3. to review, documentation

#1774 add note on sudo for windows and docker rootless
  docker-rootless.md
  readme.md
Labels: 3. to review, documentation

#1776 Prevent slow upload speeds (Reverse Proxy documentation)
  reverse-proxy.md
Labels: 3. to review, documentation

#1777 readme: clarify OS package env var
  docker-compose.yml
  readme.md
Labels: 3. to review, documentation

#1781 update Nextcloud to 25.0.3
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies

#1773 add docker cp command to prevent host file paths like /_data/
  Containers/borgbackup/backupscript.sh
  Containers/postgresql/start.sh
  manual-upgrade.md
  migration.md
  readme.md
Labels: 3. to review, documentation

#1799 Add note on Strato
  readme.md
Labels: 3. to review, documentation

#1803 adjust macOS docs about DOCKER_SOCKET_PATH
  docker-compose.yml
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, documentation

#1826 Update psalm-baseline.xml
  php/psalm-baseline.xml
  php/src/Docker/DockerActionManager.php
Labels: 3. to review

#1812 nginx proxy docs changes
  reverse-proxy.md
Labels: 3. to review, documentation

#1819 cloudflare - improve hint regarding cloudflare
  .github/ISSUE_TEMPLATE/Bug_report.md
  readme.md
Labels: 3. to review, documentation

#1820 update npm docs
  reverse-proxy.md
Labels: 3. to review, documentation

#1827 add section about recommended vps
  readme.md
Labels: 3. to review, documentation

#1818 Add a disrecommended VPS providers section
  readme.md
Labels: 3. to review, documentation

#1822 increase H2WindowSize limit (Reverse Proxy documentation)
  reverse-proxy.md
Labels: 3. to review, documentation

#1825 add section about storage options
  readme.md
Labels: 3. to review, documentation

#1813 Add Synology instructions
  php/templates/containers.twig
  readme.md
  reverse-proxy.md
Labels: 3. to review, documentation

#1791 change dind image to omit the alpine version
  Containers/mastercontainer/Dockerfile
Labels: 3. to review, dependencies

#1823 composer - add back the minor versions instead of wildcards
  php/composer.json
Labels: 3. to review, dependencies

#1817 add libpg-dev and pgsql for backup app
  Containers/nextcloud/Dockerfile
Labels: 3. to review, enhancement

#1816 remove gcompat again as it seems to break recognize
  Containers/nextcloud/Dockerfile
Labels: 3. to review, bug

#1785 clamav should never be enabled on arm64
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, bug

#1584 upgrade postgres to 15
  Containers/postgresql/Dockerfile
  Containers/postgresql/init-user-db.sh
  Containers/postgresql/start.sh
Labels: 4. to release, dependencies

#1754 Rework the traefik example
  reverse-proxy.md
Labels: 4. to release, documentation

#1834 add explanation for clamav
  php/templates/containers.twig
  readme.md
Labels: 3. to review, enhancement

#1839 follow-links should be follow-link
  migration.md
  readme.md
Labels: 3. to review, documentation

#1843 make cloudflare upload limit for explicit
  readme.md
Labels: 3. to review, documentation

#1835 imaginary - allow further mimetypees out-of-the-box
  Containers/nextcloud/entrypoint.sh
  php/templates/containers.twig
  readme.md
Labels: 3. to review, enhancement

#1845 also accept application/vnd.oci.image.index.v1+json for newer buildx …
  php/src/Docker/DockerHubManager.php
Labels: 3. to review, enhancement

#1573 migrate apache container to alpine
  Containers/apache/Dockerfile
  Containers/apache/start.sh
Labels: 3. to review, enhancement

#1577 migrate mastercontainer to alpine
  Containers/mastercontainer/Dockerfile
  Containers/mastercontainer/mastercontainer.conf
  Containers/mastercontainer/start.sh
  Containers/mastercontainer/supervisord.conf
Labels: 3. to review, enhancement

#1869 Disallow Watchtower to update AIO Container (exept Mastercontainer)
  Containers/apache/Dockerfile
  Containers/borgbackup/Dockerfile
  Containers/clamav/Dockerfile
  Containers/collabora/Dockerfile
  Containers/domaincheck/Dockerfile
  Containers/fulltextsearch/Dockerfile
  Containers/imaginary/Dockerfile
  Containers/nextcloud/Dockerfile
  Containers/onlyoffice/Dockerfile
  Containers/postgresql/Dockerfile
  Containers/redis/Dockerfile
  Containers/talk/Dockerfile
  Containers/watchtower/Dockerfile
Labels: 3. to review, enhancement

#1865 allow to copy the command to install docker
  readme.md
Labels: 3. to review, documentation
