Repository nextcloud/all-in-one, pull requests merged in 2023-03, with the labels that each got.

#2092 don't wait for clamav until forever
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#2080 fix datadir permission check
  Containers/nextcloud/entrypoint.sh
  manual-install/update-yaml.sh
  php/containers.json
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, bug

#2102 Fix directory path example
  readme.md
Labels: 3. to review, documentation

#2115 Update migration.md
  migration.md
Labels: 3. to review, documentation

#2118 only send update notifications on saturdays
  Containers/mastercontainer/cron.sh
Labels: 3. to review, enhancement

#2098 exclude nextcloud and audit log in backup due to GPDR reasons
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, enhancement

#2106 remove tzdata from mastercontainer
  Containers/mastercontainer/Dockerfile
Labels: 3. to review, enhancement

#2107 add a check if the mastercontainer volume is really connected to the mastercontainer
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#2113 fix set_memory for imaginary and move cap_add to containers.json
  php/containers-schema.json
  php/containers.json
  php/src/Container/Container.php
  php/src/ContainerDefinitionFetcher.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#2114 update some imaginary dependencies to improve performance
  Containers/imaginary/Dockerfile
Labels: 3. to review, enhancement

#2109 change how permission check setting works
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#2123 imaginary - try to prevent possible memory issues
  Containers/imaginary/Dockerfile
Labels: 3. to review, enhancement

#2122 borg script - disable globbing
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, bug

#2127 add reasons why changing volume and container name is not supported
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#2136 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
  php/psalm.xml
  php/src/Data/ConfigurationManager.php
Labels: 3. to review

#2144 nginx reverse proxy docs: disable 0-rtt
  reverse-proxy.md
Labels: 3. to review, documentation

#2149 Fix typo
  readme.md
Labels: 3. to review, documentation

#2150 fix(docs): Enforce HTTPS usage
  readme.md
Labels: 3. to review, documentation

#2152 try to update all apps a second time and try to prevent breakage
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#2135 improve hint about dns resolving
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#2134 add link about docker swarm directly to startup script
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#1583 Migrate talk container to alpine
  Containers/talk/Dockerfile
  Containers/talk/start.sh
  Containers/talk/supervisord.conf
Labels: 3. to review, enhancement

#2177 talk - stun servers may be empty
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, bug

#2183 Add even more hints to datadir permission check
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#2034 Add Helm Chart Releaser workflow
  .github/workflows/helm-release.yml
Labels: 3. to review, enhancement, upstream, blocked

#2234 add some docs on how to use helm-chart
  nextcloud-aio-helm-chart/readme.md
Labels: 3. to review, documentation

#2210 allow digits in NEXTCLOUD_STARTUP_APPS
  Containers/mastercontainer/start.sh
  readme.md
Labels: 3. to review, enhancement

#2226 increase shm_size for postgresql
  php/containers-schema.json
  php/containers.json
  php/src/Container/Container.php
  php/src/ContainerDefinitionFetcher.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#2230 improve wording of internal ip in case of reverse proxy situation
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, enhancement

#2232 fix the datadir permission problems during install
  Containers/nextcloud/entrypoint.sh
  manual-install/update-yaml.sh
  php/containers.json
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, bug

#2207 add dot to allowed characters in additional backup volumes
  php/src/Data/ConfigurationManager.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#2246 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review
