Repository nextcloud/all-in-one, pull requests merged in 2023-10, with the labels that each got.

#3463 only add container to apache container list if display_name is set
  php/src/ContainerDefinitionFetcher.php
Labels: 3. to review, enhancement

#3459 allow to set aio_variables from containers.json
  php/containers-schema.json
  php/src/Container/AioVariables.php
  php/src/Container/Container.php
  php/src/ContainerDefinitionFetcher.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#3460 community-containers - add caddy
  .github/workflows/json-validator.yml
  community-containers/caddy/caddy.json
  community-containers/caddy/readme.md
  php/containers-schema.json
Labels: 3. to review, enhancement

#3427 adjust limiting the php-fpm port to specific containers again
  Containers/docker-socket-proxy/healthcheck.sh
  Containers/docker-socket-proxy/start.sh
  Containers/nextcloud/start.sh
  Containers/nextcloud/supervisord.conf
  Containers/notify-push/healthcheck.sh
  Containers/notify-push/start.sh
  php/containers.json
Labels: 3. to review, enhancement

#3478 allow to add documentation on containers
  community-containers/caddy/caddy.json
  community-containers/fail2ban/fail2ban.json
  community-containers/pi-hole/pi-hole.json
  community-containers/plex/plex.json
  community-containers/readme.md
  community-containers/vaultwarden/vaultwarden.json
  php/containers-schema.json
  php/src/Container/Container.php
  php/src/ContainerDefinitionFetcher.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#3479 Revert dbpersistent setting to check if it fixes too many db connections
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, bug

#3480 Revert "mastercontainer - use Caddy for generating self-singed cert"
  Containers/mastercontainer/Caddyfile
  Containers/mastercontainer/Dockerfile
  Containers/mastercontainer/mastercontainer.conf
  Containers/mastercontainer/start.sh
Labels: 3. to review, bug, regression

#3481 add documentation links correctly
  php/templates/containers.twig
Labels: 3. to review, bug

#3482 overwrite APACHE_PORT, TALK_PORT and APACHE_IP_BINDING only during do…
  php/src/ContainerDefinitionFetcher.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, bug

#3469 make docker-socket-proxy visible in AIO interface
  Containers/nextcloud/entrypoint.sh
  php/templates/containers.twig
Labels: 3. to review, enhancement

#3488 allow _ping docker api to verify service accessible
  Containers/docker-socket-proxy/haproxy.cfg
Labels: 3. to review, bug

#3513 fix listen.allowed_clients in nextcloud container
  Containers/nextcloud/start.sh
Labels: 3. to review, bug

#3492 optimisations of the reverse proxy and docker rootless docs
  docker-rootless.md
  reverse-proxy.md
Labels: 3. to review, documentation

#3528 Typo in containers.twig
  php/templates/containers.twig
Labels: 3. to review, enhancement

#3522 add permanent redirect to port 80 in mastercontainer
  Containers/mastercontainer/Caddyfile
Labels: 4. to release, enhancement

#3520 Add NPMplus as community-container
  community-containers/caddy/readme.md
  community-containers/npmplus/npmplus.json
  community-containers/npmplus/readme.md
Labels: 4. to release, enhancement

#3523 reduce size of talk image
  Containers/talk/Dockerfile
Labels: 3. to review, enhancement

#3545 fix regex for additional backup dirs
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, bug

#3495 community containers - add local ai
  community-containers/local-ai/local-ai.json
  community-containers/local-ai/readme.md
  community-containers/readme.md
Labels: 3. to review, enhancement

#3515 do not expose udp if AIO is in reverse prox mode
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#3555 rework local-ai to download models automatically
  community-containers/local-ai/local-ai.json
  community-containers/local-ai/readme.md
Labels: 3. to review, enhancement

#3556 local-ai - actually do not back up downloaded models
  community-containers/local-ai/local-ai.json
  community-containers/local-ai/readme.md
Labels: 3. to review, enhancement

#3568 add hint regarding community containers to the AIO interface
  php/templates/containers.twig
Labels: 3. to review, enhancement

#3567 add maxconn value to haproxy
  Containers/docker-socket-proxy/haproxy.cfg
Labels: 3. to review, bug

#3565 community containers - add libretranslate container
  community-containers/libretranslate/libretranslate.json
  community-containers/libretranslate/readme.md
  community-containers/readme.md
Labels: 3. to review, enhancement

#3550 Add more compose presets and fix typos
  compose.yaml
  reverse-proxy.md
Labels: 3. to review, documentation

#3574 nextcloud container - allowed clients - only limit access in known use cases
  Containers/nextcloud/start.sh
  php/containers.json
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, bug

#3583 do not catch error during pullcontainer so that it throws and logs if it cannot get the image
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#3584 postgresql - close idling sessions automatically and increase to 100 default
  Containers/postgresql/start.sh
Labels: 3. to review, enhancement

#3608 change priority of app-settings-section to 0
  app/lib/Settings/Admin.php
Labels: 3. to review, enhancement

#3639 local-ai - fix path to generated images
  community-containers/local-ai/local-ai.json
Labels: 3. to review, bug

#3641 also enable integration apps after installing them
  community-containers/libretranslate/libretranslate.json
  community-containers/local-ai/local-ai.json
Labels: 3. to review, enhancement

#3594 fix reference to column in wikipedia timezone list
  Containers/postgresql/start.sh
  php/templates/containers.twig
Labels: 3. to review, enhancement

#3642 allow to back up empty additional volumes
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, enhancement

#3611 add AIO_DATABASE_HOST
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#3610 Update migration.md with info about synchronization
  migration.md
Labels: 3. to review, documentation

#3614 Nextcloud-DLNA community container
  community-containers/dlna/dlna.json
  community-containers/dlna/readme.md
Labels: 3. to review, enhancement
