Repository nextcloud/all-in-one, pull requests merged in 2023-11, with the labels that each got.

#3656 Update reverse-proxy.md typo
  reverse-proxy.md
Labels: 3. to review, documentation

#3659 rewording reverse-proxy.md
  reverse-proxy.md
Labels: 3. to review, documentation

#3666 fix some values
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/entrypoint.sh
  Containers/postgresql/start.sh
Labels: 3. to review, enhancement

#3686 community containers - add docs how to remove containers
  community-containers/readme.md
Labels: 3. to review, documentation

#3685 pi-hole does not like init
  community-containers/pi-hole/pi-hole.json
Labels: 3. to review, bug

#3690 create helm-beta release
  nextcloud-aio-helm-chart/Chart.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-clamav-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-collabora-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-database-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-fulltextsearch-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-imaginary-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-notify-push-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-onlyoffice-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-redis-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-recording-deployment.yaml
Labels: 3. to review, dependencies

#3693 disaable limiting the listen.allowed clients again
  Containers/nextcloud/start.sh
Labels: 3. to review, enhancement

#3694 helm - change defaults of NEXTCLOUD*STORAGE_SIZE
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, enhancement

#3682 do not start container if it is started already
  php/src/Controller/DockerController.php
Labels: 3. to review, bug

#3701 change externaltrafficpolicy
  nextcloud-aio-helm-chart/Chart.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-service.yaml
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review

#3705 fix getting ip-address
  Containers/talk/Dockerfile
  Containers/talk/start.sh
Labels: 3. to review, bug

#3707 make sure that notify-push is executable
  Containers/notify-push/start.sh
Labels: 3. to review, enhancement

#3736 community containers - add memories
  community-containers/memories/memories.json
  community-containers/memories/readme.md
Labels: 3. to review, enhancement

#3751 log whole error messages
  php/public/index.php
  php/src/Cron/StartAndUpdateContainers.php
  php/src/Cron/StartContainers.php
Labels: 3. to review, enhancement

#3734 add JSON_THROW_ON_ERROR to json_encode and json_decode in config manager
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, enhancement

#3752 get recording server from its repo
  .github/workflows/talk.yml
  Containers/talk-recording/Dockerfile
  Containers/talk-recording/recording.conf
  Containers/talk-recording/start.sh
Labels: 3. to review, enhancement

#3735 re-introduce limiting the php-fpm port to certain containers
  Containers/nextcloud/entrypoint.sh
  Containers/nextcloud/start.sh
  manual-install/update-yaml.sh
  php/containers.json
Labels: 3. to review, enhancement

#3758 Revert "Bump elasticsearch from 8.11.0 to 8.11.1 in /Containers/fullt…
  Containers/fulltextsearch/Dockerfile
Labels: 3. to review, dependencies

#3760 helm chart - create beta release
  nextcloud-aio-helm-chart/Chart.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-clamav-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-collabora-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-database-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-fulltextsearch-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-imaginary-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-notify-push-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-onlyoffice-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-redis-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-recording-deployment.yaml
Labels: 3. to review, dependencies

#3783 helm: fix duplicate SMTP_HOST env variable
  nextcloud-aio-helm-chart/Chart.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-service.yaml
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, enhancement

#3784 helm-chart - fix clamav permissions
  nextcloud-aio-helm-chart/Chart.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-clamav-deployment.yaml
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, enhancement

#3801 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review, dependencies

#3781 add mknod capability to collabora
  php/containers.json
Labels: 3. to review, enhancement

#3773 rename pullContainer to pullImage
  php/src/Controller/DockerController.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#3774 Make sure that image is correctly pulled before continuing
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#3795 helm - allow to define an additional_trusted_proxy
  Containers/nextcloud/entrypoint.sh
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, enhancement

#3804 helm - publish new dev release
  nextcloud-aio-helm-chart/Chart.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
Labels: 3. to review, dependencies

#3792 helm - remove lost+found in nextcloud
  nextcloud-aio-helm-chart/Chart.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-collabora-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, enhancement

#3832 add a hint about what is getting backed up when using aios backup sol…
  readme.md
Labels: 3. to review, documentation

#3826 Minor English grammar fixes in readme.md
  readme.md
Labels: 3. to review, documentation
