Repository nextcloud/all-in-one, pull requests merged in 2023-07, with the labels that each got.

#2888 documentation: misspelling
  reverse-proxy.md
Labels: 3. to review, documentation

#2926 imaginary - add tmpfs in /tmp
  php/containers.json
Labels: 3. to review, bug

#2930 Remove warning about Docker Desktop v4.19
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#2922 coturn - pin alpine version correctly
  Containers/talk/Dockerfile
Labels: 3. to review, enhancement, dependencies

#2931 Fix cp command in migration.md
  migration.md
Labels: 3. to review, documentation

#2870 make domaincheck container read-only
  Containers/domaincheck/Dockerfile
  Containers/domaincheck/start.sh
  php/containers.json
Labels: 3. to review, enhancement

#2871 make postgresql container read-only
  Containers/postgresql/Dockerfile
  php/containers.json
Labels: 3. to review, enhancement

#2872 make collabora container read-only
  Containers/collabora/Dockerfile
  php/containers-schema.json
  php/containers.json
Labels: 3. to review, enhancement

#2875 make talk container read-only
  Containers/talk/Dockerfile
  Containers/talk/start.sh
  Containers/talk/supervisord.conf
  php/containers.json
Labels: 3. to review, enhancement

#2876 make talk-recording read-only
  Containers/talk-recording/Dockerfile
  Containers/talk-recording/start.sh
  php/containers.json
Labels: 3. to review, enhancement

#2874 make apache container read-only
  Containers/apache/Dockerfile
  Containers/apache/start.sh
  Containers/apache/supervisord.conf
  php/containers-schema.json
  php/containers.json
Labels: 3. to review, enhancement

#2952 Revert "make collabora container read-only"
  Containers/collabora/Dockerfile
  php/containers.json
Labels: 3. to review, regression

#2975 adjust helm-update script
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, enhancement

#2886 build janus 0.x
  .github/workflows/talk.yml
  Containers/talk/Dockerfile
  Containers/talk/supervisord.conf
Labels: 3. to review, enhancement, dependencies

#2880 talk-recording - set allow_all and skip_verify via env
  Containers/talk-recording/Dockerfile
  Containers/talk-recording/start.sh
Labels: 3. to review, enhancement

#2700 update to ES 8 and add necessary adjustements to its config
  Containers/fulltextsearch/Dockerfile
  php/containers.json
Labels: 3. to review, dependencies

#2971 remove cgi-bin scripts
  Containers/apache/Dockerfile
  Containers/mastercontainer/Dockerfile
Labels: 3. to review, enhancement

#2981 nextcloud container - make /tmp a tmpfs
  Containers/nextcloud/Dockerfile
  php/containers.json
Labels: 3. to review, enhancement

#2983 display warning if domaincheck container could not be started instead of bugging out
  php/containers.json
  php/public/index.php
  php/src/Controller/DockerController.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#2601 set NEXTCLOUD_MOUNT to rshared
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#3017 Update manual-upgrade.md shebang
  manual-upgrade.md
Labels: 3. to review, documentation

#3021 make database connections persistant
  Containers/nextcloud/config/postgresql.php
  Containers/nextcloud/start.sh
Labels: 3. to review, enhancement

#3000 talk-recording - allow to set hpb_domain and nc_domain independently
  Containers/talk-recording/start.sh
Labels: 3. to review, enhancement
