Repository nextcloud/all-in-one, pull requests merged in 2023-05, with the labels that each got.

#2442 add twig-lint
  .github/workflows/twig-lint.yml
Labels: 3. to review

#2419 add a hint where to look at in rp doc
  php/templates/containers.twig
Labels: 3. to review, enhancement

#2427 Krita should be enabled by default
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#2416 adjust the button color on focus
  php/public/forms.js
  php/public/style.css
Labels: 3. to review, enhancement

#2431 mastercontainer - delete things except the needed php dir
  Containers/mastercontainer/Dockerfile
Labels: 3. to review, enhancement

#2432 add apparmor_unconinfed to containers definition
  php/containers-schema.json
  php/containers.json
  php/src/Container/Container.php
  php/src/ContainerDefinitionFetcher.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#2446 collabora - make startup faster by not generating ssl cert
  php/containers.json
Labels: 3. to review, enhancement

#2329 RP docs - add Citrix ADC VPX / Citrix Netscaler
  reverse-proxy.md
Labels: 3. to review, documentation

#2456 updaate regex for some values in containers schema
  php/containers-schema.json
Labels: 3. to review, enhancement

#2453 Fix typo in HTML template: changed "duckduckdns.org" to "duckdns.org"
  php/templates/containers.twig
Labels: 3. to review, bug

#2467 put the database into a subpath
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, bug

#2459 run composer during install as non-root user
  Containers/mastercontainer/Dockerfile
Labels: 3. to review, enhancement

#2473 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review, dependencies

#2477 helm-chart - create the data folder manually in order to apply the co…
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, bug

#2476 manual-install - enable ipv6 by default
  manual-install/update-yaml.sh
Labels: 3. to review, enhancement

#2482 nextcloud-aio network - remove non-default options
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#2492 optimize clamav Dockerfile
  Containers/clamav/Dockerfile
Labels: 3. to review, enhancement

#2494 optimze domaincheck Dockerfile
  Containers/domaincheck/Dockerfile
Labels: 3. to review, enhancement

#2499 optimize redis Dockerfile
  Containers/redis/Dockerfile
Labels: 3. to review, enhancement

#2500 optimize talk Dockerfile
  Containers/talk/Dockerfile
Labels: 3. to review, enhancement

#2491 optimize borg dockerfile
  Containers/borgbackup/Dockerfile
Labels: 3. to review, enhancement

#2502 add a second init step for postgres
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, bug

#2495 optimze elastic Dockerfile
  Containers/fulltextsearch/Dockerfile
Labels: 3. to review, enhancement

#2488 try to speed up the initial login
  php/public/index.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#2485 talk - remove lt-cred-mech as that is not recommended anymore
  Containers/talk/start.sh
Labels: 3. to review, bug

#2481 document how to enable ipv6 for the internal network
  docker-ipv6-support.md
Labels: 3. to review, documentation

#2470 revert disabling FTS if on Nc26
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#2483 add internal network config to docker-compose file as well
  docker-compose.yml
Labels: 3. to review, documentation

#2504 improve ipv6 docs
  docker-compose.yml
  docker-ipv6-support.md
  manual-install/update-yaml.sh
Labels: 3. to review, documentation

#2340 Proxy instructions for NodeJS/express
  reverse-proxy.md
Labels: 3. to review, documentation

#2512 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review, dependencies

#2514 Update local-instance.md
  local-instance.md
Labels: 3. to review, documentation

#2535 add r0 to coturn version
  Containers/talk/Dockerfile
Labels: 3. to review, dependencies

#2536 update mastercontainer to php 8.2
  .github/workflows/create-psalm-container.yml
  .github/workflows/dependency-updates.yml
  .github/workflows/lint-php.yml
  .github/workflows/php-deprecation-detector.yml
  .github/workflows/psalm-analysis.yml
  .github/workflows/psalm-update-baseline.yml
  .github/workflows/twig-lint.yml
  Containers/mastercontainer/Dockerfile
  php/composer.json
  php/composer.lock
Labels: 3. to review, dependencies

#2519 add root user check for mastercontainer
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#2520 backup script - a few enhancements and safeguards
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, enhancement, borg

#2539 try to fix the helm-chart-update workflow
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, bug

#2545 sudo docker volume prune --filter all=1
  readme.md
Labels: 3. to review, documentation

#2541 Makes imaginary port configurable
  Containers/imaginary/Dockerfile
Labels: 3. to review, enhancement

#2496 optimze mastercontainer Dockerfile
  Containers/mastercontainer/Dockerfile
Labels: 3. to review, enhancement

#2455 allow to include volumes in backup and restore
  Containers/borgbackup/backupscript.sh
  manual-install/update-yaml.sh
  php/containers-schema.json
  php/containers.json
  php/src/Container/Container.php
  php/src/ContainerDefinitionFetcher.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#2490 optimze apache dockerfile
  Containers/apache/Dockerfile
Labels: 3. to review, enhancement

#2457 allow to add imports to the caddy file
  Containers/apache/Caddyfile
  Containers/apache/Dockerfile
  Containers/apache/caddy-imports/collabora
  Containers/apache/caddy-imports/notify-push
  Containers/apache/caddy-imports/onlyoffice
  Containers/apache/caddy-imports/talk
  Containers/apache/nextcloud
  Containers/apache/start.sh
Labels: 3. to review, enhancement

#2565 fix getAllBackupVolumes
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, bug

#2569 caddy - a bugfix and some improvements
  Containers/apache/Caddyfile
  Containers/apache/Dockerfile
  Containers/apache/caddy-imports/collabora
  Containers/apache/caddy-imports/notify-push
  Containers/apache/caddy-imports/onlyoffice
  Containers/apache/caddy-imports/talk
  Containers/apache/nextcloud
  Containers/apache/start.sh
Labels: 3. to review, bug, high, regression

#2586 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review, dependencies

#2580 Update reverse-proxy.md
  reverse-proxy.md
Labels: 3. to review, documentation

#2613 chore: update workflows from templates
  .github/workflows/command-rebase.yml
  .github/workflows/lint-php.yml
Labels: 3. to review, dependencies, automated

#2611 validate json against json schema
  php/composer.json
  php/composer.lock
  php/src/ContainerDefinitionFetcher.php
Labels: 3. to review, enhancement

#2576 enable compression for js files in Nextcloud
  Containers/apache/Dockerfile
  Containers/apache/nextcloud.conf
  readme.md
Labels: 3. to review, enhancement

#2573 clear apcu cache upon starting containers
  php/src/Controller/DockerController.php
Labels: 3. to review, enhancement

#2428 allow to adjust borgs retention policy
  Containers/borgbackup/Dockerfile
  Containers/borgbackup/backupscript.sh
  docker-compose.yml
  php/containers.json
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#2602 update to Nextcloud 26.0.2
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies

#2603 increase supported aio app versions
  app/appinfo/info.xml
Labels: 3. to review, dependencies

#2604 set newMajorVersion to empty string
  php/templates/containers.twig
Labels: 3. to review, enhancement

#2605 update Nextcloud container to php 8.1 and alpine 3.17
  Containers/nextcloud/Dockerfile
  readme.md
Labels: 3. to review, dependencies

#2608 remove imaginary version check
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#2609 add notes app to default apps
  docker-compose.yml
  manual-install/sample.conf
  manual-install/update-yaml.sh
  php/src/Data/ConfigurationManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#2454 allow to define nextcloud_exec_commands in containers definition
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/activate-collabora.sh
  Containers/nextcloud/run-exec-commands.sh
  Containers/nextcloud/supervisord.conf
  manual-install/update-yaml.sh
  php/containers-schema.json
  php/containers.json
  php/src/Container/Container.php
  php/src/ContainerDefinitionFetcher.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#2621 rework getbackupvolumes and getallbackupvolumes to be a bit more easy…
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement
