Repository nextcloud/all-in-one, pull requests merged in 2023-06, with the labels that each got.

#2668 add http/3 docs to nginx reverse proxy docs
  reverse-proxy.md
Labels: 3. to review, documentation

#2645 add talk-recording container
  .github/dependabot.yml
  .github/workflows/talk.yml
  Containers/talk-recording/Dockerfile
  Containers/talk-recording/recording.conf
  Containers/talk-recording/start.sh
  Containers/talk/Dockerfile
  Containers/talk/start.sh
Labels: 3. to review, enhancement

#2672 janus - enable full-trickle support
  Containers/talk/supervisord.conf
Labels: 3. to review, enhancement

#2670 add note about SELinux and Docker Desktop
  Containers/mastercontainer/start.sh
  readme.md
Labels: 3. to review, documentation, enhancement

#2661 Dockerfiles - Add USER to all files
  Containers/apache/Dockerfile
  Containers/borgbackup/Dockerfile
  Containers/clamav/Dockerfile
  Containers/fulltextsearch/Dockerfile
  Containers/mastercontainer/supervisord.conf
  Containers/nextcloud/Dockerfile
  Containers/onlyoffice/Dockerfile
  Containers/watchtower/Dockerfile
Labels: 3. to review, enhancement

#2663 update-yml.sh - remove unit for stop_grace_period
  manual-install/update-yaml.sh
Labels: 3. to review, enhancement

#2658 remove the updatenotification app also if already updating to next ma…
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#2653 Remove collaboras font volume as it does not seem to be used
  php/containers.json
Labels: 3. to review, enhancement

#2639 Switch from mawk to built-in awk
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/entrypoint.sh
  Containers/postgresql/Dockerfile
  Containers/postgresql/start.sh
Labels: 4. to release, enhancement

#2660 Make sure to disable apps that could not get enabled after an update
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#2631 add profiles and networks to container-schema.json
  manual-install/update-yaml.sh
  php/containers-schema.json
  php/containers.json
Labels: 3. to review, enhancement

#2664 try to speed up initial login by not removing the bridge network from…
  Containers/mastercontainer/cron.sh
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#2679 Move vars to lets and fix some things with recording.conf
  Containers/talk-recording/Dockerfile
  php/public/automatic_reload.js
  php/public/disable-clamav.js
  php/public/disable-collabora.js
  php/public/disable-fulltextsearch.js
  php/public/disable-imaginary.js
  php/public/disable-onlyoffice.js
  php/public/disable-talk.js
  php/public/forms.js
  php/public/options-form-submit.js
  php/templates/containers.twig
Labels: 3. to review, bug

#2652 update ES to 8.x
  Containers/fulltextsearch/Dockerfile
Labels: 3. to review, dependencies

#2685 allow to install 27 on new install
  php/src/Controller/DockerController.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#2693 Revert "update ES to 8.x"
  Containers/fulltextsearch/Dockerfile
Labels: 3. to review, bug

#2624 update aio-backup-archive test archive
  tests/QA/assets/backup-archive/readme.md
Labels: 3. to review

#2749 fix a detail with the helm chart
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, bug

#2765 update nginx reverse proxy docs for nginx v1.25.1
  reverse-proxy.md
Labels: 3. to review, documentation

#2768 update all container to alpine v3.18.3
  Containers/apache/Dockerfile
  Containers/borgbackup/Dockerfile
  Containers/domaincheck/Dockerfile
  Containers/imaginary/Dockerfile
  Containers/mastercontainer/Dockerfile
  Containers/nextcloud/Dockerfile
  Containers/talk/Dockerfile
  Containers/watchtower/Dockerfile
  readme.md
Labels: 3. to review, dependencies

#2706 make watchtower read-only
  php/containers.json
Labels: 3. to review, enhancement

#2707 adjust janus debug-level to 3 = warn
  Containers/talk/supervisord.conf
Labels: 3. to review, enhancement

#2709 adjust postgres conf to not log checkpoints
  Containers/postgresql/Dockerfile
Labels: 3. to review, enhancement

#2698 adjust spacing of elements
  php/templates/containers.twig
  php/templates/includes/aio-config.twig
Labels: 3. to review, design, enhancement

#2762 adjust opcache and jit values
  Containers/nextcloud/Dockerfile
Labels: 3. to review, enhancement

#2731 some general improvements to buttons and AIO interface
  php/templates/containers.twig
Labels: 3. to review, enhancement

#2730 Allow to reset the borg backup host location before initial backup was started
  php/src/Controller/ConfigurationController.php
  php/src/Data/ConfigurationManager.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#2772 Revert "make borgbackup read-only"
  php/containers.json
Labels: 3. to review, bug, regression

#2778 Nginx reverse proxy docs again
  reverse-proxy.md
Labels: 3. to review, documentation

#2725 add run_upgrade_if_needed_due_to_app_update
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#2783 make imaginary read-only
  php/containers.json
Labels: 3. to review, enhancement

#2784 only modify postgresql.conf if it exists
  Containers/postgresql/start.sh
Labels: 3. to review, bug

#2786 Make clear that Cloudflare Tunnel is also a reverse proxy
  compose.yaml
  manual-install/sample.conf
  manual-install/update-yaml.sh
  nextcloud-aio-helm-chart/values.yaml
  php/templates/containers.twig
  readme.md
  reverse-proxy.md
Labels: 3. to review, documentation, enhancement

#2788 Update spellcheck.yml
  .github/workflows/codespell.yml
  .github/workflows/spellcheck.yml
  compose.yaml
  local-instance.md
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
  readme.md
  tests/QA/060-environmental-variables.md
  tests/QA/070-timezone-change.md
Labels: 3. to review, enhancement

#2793 also compress css and svg files
  Containers/apache/nextcloud.conf
  readme.md
Labels: 3. to review, enhancement

#2794 Adjust Apache LogFormat
  Containers/apache/nextcloud.conf
Labels: 3. to review, enhancement

#2796 fix and adjust mastercontainer apache logging
  Containers/mastercontainer/Dockerfile
  Containers/mastercontainer/mastercontainer.conf
Labels: 3. to review, bug

#2800 add docs on how to run AIO on TrueNas Scale
  Containers/mastercontainer/start.sh
  readme.md
Labels: 3. to review, documentation, enhancement

#2807 coturn container - pin alpine version manually
  Containers/talk/Dockerfile
Labels: 3. to review, enhancement, dependencies

#2797 talk and redis - adjust location of entrypoints
  Containers/redis/Dockerfile
  Containers/talk/Dockerfile
Labels: 3. to review, enhancement

#2812 Make borgbackup read-only
  php/containers-schema.json
  php/containers.json
Labels: 3. to review, enhancement

#2813 make clamav read-only
  Containers/clamav/Dockerfile
  php/containers.json
Labels: 3. to review, enhancement

#2852 add back instructions about huge docker logs
  readme.md
Labels: 3. to review, documentation

#2861 disable watchtower pulling for containers
  Containers/apache/Dockerfile
  Containers/borgbackup/Dockerfile
  Containers/clamav/Dockerfile
  Containers/collabora/Dockerfile
  Containers/domaincheck/Dockerfile
  Containers/fulltextsearch/Dockerfile
  Containers/imaginary/Dockerfile
  Containers/nextcloud/Dockerfile
  Containers/notify-push/Dockerfile
  Containers/onlyoffice/Dockerfile
  Containers/postgresql/Dockerfile
  Containers/redis/Dockerfile
  Containers/talk-recording/Dockerfile
  Containers/talk/Dockerfile
  Containers/watchtower/Dockerfile
Labels: 3. to review, enhancement

#2817 remove r3 from coturn version
  Containers/talk/Dockerfile
Labels: 3. to review, enhancement, dependencies

#2815 add note to AIO interface that imaginary is incompatible with SSE
  php/templates/containers.twig
Labels: 3. to review, enhancement

#2826 mastercontainer - disable http3
  Containers/mastercontainer/Caddyfile
Labels: 3. to review, enhancement

#2828 apache - expose udp for http3 to work
  php/containers.json
  php/templates/containers.twig
  readme.md
Labels: 3. to review, documentation, enhancement

#2842 small improvement to files_antivirus settings
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#2857 add logging in case disk space is low and thus login might fail
  php/src/Auth/AuthManager.php
Labels: 3. to review, enhancement

#2858 add low-on-space notification
  Containers/mastercontainer/cron.sh
  php/src/Cron/CheckFreeDiskSpace.php
Labels: 3. to review, enhancement

#2867 adjust migration docs
  migration.md
Labels: 3. to review, documentation

#2873 adjust wording for backup time
  php/templates/containers.twig
Labels: 3. to review, enhancement

#2868 revert adjustment of tempdirectory
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#2787 show AIO password
  php/public/forms.js
  php/templates/containers.twig
  php/templates/login.twig
Labels: 3. to review, enhancement

#2869 rework notify-push in order to export values as env
  Containers/notify-push/start.sh
Labels: 3. to review, enhancement

#2878 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review, dependencies

#2882 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review, dependencies
