Repository nextcloud/all-in-one, pull requests merged in 2024-01, with the labels that each got.

#3931 Unify `<your-nc-domain>` throughout the doc
  reverse-proxy.md
Labels: 3. to review, documentation

#3941 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review, dependencies

#3972 Add context to custom skeleton directory howto in readme
  readme.md
Labels: 3. to review, documentation

#3992 talk-recording - re-add secret to backend conf
  Containers/talk-recording/start.sh
Labels: 3. to review, enhancement

#4018 Update readme.md mistypo
  community-containers/stalwart/readme.md
Labels: 3. to review, documentation

#3999 community-containers - add facerecognition
  community-containers/facerecognition/facerecognition.json
  community-containers/facerecognition/readme.md
  readme.md
Labels: 3. to review, enhancement

#4024 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review, dependencies

#4021 borgbackup - add check for .ocdata file for datadir
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, enhancement, borg

#4028 notify-push - fix postgres_user variable
  Containers/notify-push/start.sh
Labels: 3. to review, bug

#3965 Add Treafik HTTP/3 Support
  reverse-proxy.md
Labels: 3. to review, documentation

#4046 Make port 443 error message more verbose
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, enhancement

#4047 disable SELinux for AIO containers
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#4048 inverse the addition of imagemagick by deleting it if it was not added
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/start.sh
Labels: 3. to review, enhancement

#4050 point at debug documentation if AIO is in RP mode
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, enhancement

#4052 Update notice about Strato VPSs
  readme.md
Labels: 3. to review, documentation

#4054 apache - adjust MaxRequestWorkers and ServerLimit
  Containers/apache/Dockerfile
  Containers/nextcloud/Dockerfile
  Containers/postgresql/start.sh
Labels: 3. to review, enhancement

#4060 improve the reserved ip-address notice
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, enhancement

#4061 improve the hint what to do if access on 443 is blocked
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, enhancement

#4065 add further hint for what could be wrong
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#4066 only check if the image is actually there if no image is there
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#4071 Increase version of the facerecognition external model to v1.
  community-containers/facerecognition/facerecognition.json
Labels: 3. to review, dependencies

#4083 Reword the error message shown when the password is incorrect
  php/src/Controller/LoginController.php
Labels: 3. to review, enhancement

#4090 [Automated] Update psalm-baseline.xml
  php/domain-validator.php
  php/psalm-baseline.xml
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, dependencies

#4111 allow to add nextcloud-aio-caddy ip-address to trusted proxies automatically
  manual-install/update-yaml.sh
  php/containers.json
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#4113 nextcloud - update to 27.1.6
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies

#4130 fix borg backup restore not working anymore
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, bug, high, borg

#4119 downgrade back to 27.1.5
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies
