Repository nextcloud/all-in-one, pull requests merged in 2024-09, with the labels that each got.

#5181 nextcloud-entrypoint: remove richdocumentscode if installed
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#5200 Revert "Nextcloud dependency update"
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies

#5201 Revert "Revert "Nextcloud dependency update""
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies

#5202 nextcloud-entrypoint: maintenance-repair: include-expensive
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#5203 aio-interface: allow to install nc 30 directly
  php/src/Controller/DockerController.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#5253 readme.md: add section how to contribute
  readme.md
Labels: 3. to review, documentation

#5250 borgbackup: also check for .ncdata
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, bug, borg

#5275 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review, dependencies

#5274 add whiteboard container
  .github/dependabot.yml
  Containers/apache/Caddyfile
  Containers/nextcloud/entrypoint.sh
  Containers/whiteboard/Dockerfile
  Containers/whiteboard/start.sh
  manual-install/readme.md
  php/containers.json
  php/public/disable-whiteboard.js
  php/public/index.php
  php/public/options-form-submit.js
  php/src/ContainerDefinitionFetcher.php
  php/src/Controller/ConfigurationController.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
  readme.md
Labels: 3. to review, enhancement

#5279 whiteboard: make the container read-only
  php/containers.json
Labels: 3. to review, enhancement

#5298 readme: update screenshots
  readme.md
Labels: 3. to review, documentation

#5297 docs: remove hint that network_mode host does not work on Docker Desktop
  community-containers/dlna/readme.md
  community-containers/fail2ban/readme.md
  community-containers/jellyfin/readme.md
  community-containers/npmplus/readme.md
  community-containers/plex/readme.md
Labels: 3. to review, documentation

#5319 aio-interface: use Nextcloud Hub naming scheme
  php/templates/containers.twig
Labels: 3. to review, enhancement

#5321 dependabot: condense docker update list
  .github/dependabot.yml
Labels: 3. to review, dependencies

#5293 aio-interface: setup.twig: remove whitespace after br, before span tag
  php/templates/setup.twig
Labels: 3. to review, enhancement

#5306 Update containers.json to fix inter-container-connectivity
  php/containers.json
Labels: 3. to review, enhancement

#5344 memories: add NEXTCLOUD_MOUNT to CC
  community-containers/memories/memories.json
Labels: 3. to review, enhancement
