Repository nextcloud/all-in-one, pull requests merged in 2024-12, with the labels that each got.

#5673 DockerActionManager: improve PullImage to always log something if it fails
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#5672 nextcloud: always enable ImaginaryPDF
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#5689 containers-schema.json: add healtchecks
  Containers/collabora/Dockerfile
  Containers/collabora/healthcheck.sh
  Containers/fulltextsearch/Dockerfile
  Containers/fulltextsearch/healthcheck.sh
  Containers/imaginary/Dockerfile
  Containers/imaginary/healthcheck.sh
  Containers/nextcloud/Dockerfile
  Containers/onlyoffice/Dockerfile
  Containers/onlyoffice/healthcheck.sh
  Containers/redis/Dockerfile
  Containers/redis/healthcheck.sh
  Containers/talk-recording/Dockerfile
  Containers/talk-recording/healthcheck.sh
  Containers/whiteboard/Dockerfile
  Containers/whiteboard/healthcheck.sh
  nextcloud-aio-helm-chart/update-helm.sh
  php/containers-schema.json
  php/containers.json
Labels: 3. to review, enhancement

#5688 collabora: configure net.post_allow_host
  php/containers.json
Labels: 3. to review, bug

#5671 nextcloud: allow to adjust name of nextcloud container
  Containers/nextcloud/entrypoint.sh
  php/containers.json
Labels: 3. to review, enhancement

#5705 nextcloud: increase to 30.0.3
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies

#5718 nextcloud entrypoint: fix missing apostroph in require command
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, bug

#5739 nextcloud: update to 30.0.4
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies

#5736 talk: update Janus to 1.x
  .github/workflows/talk.yml
  Containers/talk/Dockerfile
Labels: 3. to review, enhancement

#5759 update remaining docker images to alpine 3.21
  Containers/apache/Dockerfile
  Containers/imaginary/Dockerfile
  Containers/mastercontainer/Dockerfile
  Containers/nextcloud/Dockerfile
  Containers/postgresql/Dockerfile
  Containers/talk-recording/Dockerfile
  readme.md
Labels: 3. to review, dependencies

#5761 adjust start-period and retries for fts, collabora and clamav
  Containers/clamav/Dockerfile
  Containers/collabora/Dockerfile
  Containers/onlyoffice/Dockerfile
  manual-install/latest.yml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-clamav-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-collabora-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-onlyoffice-deployment.yaml
  php/containers.json
Labels: 3. to review, enhancement

#5751 Add NPMplus to reverse-proxy.md
  reverse-proxy.md
Labels: 3. to review, documentation

#5570 Add documentation on migrating using the borg backup
  migration.md
  readme.md
Labels: 3. to review, documentation

#5750 Improve nginx reverse proxy template
  reverse-proxy.md
Labels: 3. to review, documentation

#5767 rp-docs: add comment to the config directly to adjust localhost:11000
  reverse-proxy.md
Labels: 3. to review, documentation

#5132 add support for nvidia gpu access
  community-containers/facerecognition/facerecognition.json
  community-containers/jellyfin/jellyfin.json
  community-containers/local-ai/local-ai.json
  community-containers/memories/memories.json
  community-containers/memories/readme.md
  community-containers/plex/plex.json
  compose.yaml
  manual-install/update-yaml.sh
  php/containers-schema.json
  php/containers.json
  php/public/index.php
  php/src/Container/Container.php
  php/src/ContainerDefinitionFetcher.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  php/templates/includes/aio-config.twig
  readme.md
Labels: 3. to review, enhancement

#5775 disable fts if seccomp is not supported in the kernel
  php/src/Data/ConfigurationManager.php
  php/templates/includes/optional-containers.twig
Labels: 3. to review, enhancement

#5730 Add apache container reachability check and retry mechanism to run-exec-commands.sh
  Containers/nextcloud/run-exec-commands.sh
  manual-install/latest.yml
  php/containers.json
Labels: 3. to review, enhancement

#5772 aio-interface: adjust design of buttons according Nextcloud Vue
  php/public/style.css
  php/templates/layout.twig
Labels: 3. to review, enhancement

#5781 actually fix collabora
  Containers/collabora/Dockerfile
  php/containers.json
Labels: 3. to review, bug

#5793 rp-docs: comments out http3_stream_buffer_size 512k in nginx template
  reverse-proxy.md
Labels: 3. to review, documentation
