Repository nextcloud/all-in-one, pull requests merged in 2024-06, with the labels that each got.

#4755 revert "set NEXTCLOUD_MOUNT to rshared #2601"
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, bug

#4742 facerecognition: change to FACE_MODEL=3 and adjust memory values
  community-containers/facerecognition/facerecognition.json
Labels: 3. to review, enhancement

#4724 use `127.0.0.1` instead of `localhost`
  Containers/apache/Caddyfile
  Containers/apache/healthcheck.sh
  Containers/collabora/Dockerfile
  Containers/docker-socket-proxy/healthcheck.sh
  Containers/domaincheck/Dockerfile
  Containers/fulltextsearch/Dockerfile
  Containers/imaginary/Dockerfile
  Containers/mastercontainer/Caddyfile
  Containers/mastercontainer/healthcheck.sh
  Containers/mastercontainer/mastercontainer.conf
  Containers/nextcloud/healthcheck.sh
  Containers/notify-push/healthcheck.sh
  Containers/onlyoffice/Dockerfile
  Containers/postgresql/healthcheck.sh
  Containers/postgresql/start.sh
  Containers/talk-recording/Dockerfile
  Containers/talk/healthcheck.sh
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#4769 nextcloud: increase the default_socket_timeout
  Containers/nextcloud/Dockerfile
Labels: 3. to review, enhancement

#4770 aio-app: increase version
  app/appinfo/info.xml
Labels: 3. to review, dependencies

#4771 aio-interface: hide upgrade notice
  php/templates/containers.twig
Labels: 3. to review, enhancement

#4772 postgres: update to 16
  Containers/postgresql/Dockerfile
Labels: 3. to review, dependencies

#4773 nextcloud: increase to 29.0.2
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies

#4774 caddy: fix rewriting .well-known to remote.php
  Containers/apache/Caddyfile
Labels: 3. to review, enhancement

#4779 talk: disable specific health check because it is not going to work o…
  Containers/talk/healthcheck.sh
Labels: 3. to review, bug

#4753 Update add admin token
  community-containers/stalwart/readme.md
  community-containers/stalwart/stalwart.json
Labels: 3. to review, enhancement

#4783 aio interface: add hint what to do if daily backup gets stuck
  php/templates/containers.twig
Labels: 3. to review, enhancement

#4799 readme: improve grammar
  readme.md
Labels: 3. to review, documentation

#4789 fix getting ip-address of talk and apache
  Containers/apache/start.sh
  Containers/talk/start.sh
  php/containers.json
Labels: 3. to review, bug

#4807 nextcloud: improve getting values for APPSTORAGE
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#4829 trusted-proxies: trust docker network
  Containers/apache/start.sh
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, bug

#4811 Stalwart: Change maintainer
  community-containers/stalwart/readme.md
  community-containers/stalwart/stalwart.json
Labels: 3. to review, enhancement

#4813 nextcloud: add igbinary as serializer for increased performance
  .github/workflows/nextcloud-update.yml
  Containers/nextcloud/Dockerfile
Labels: 3. to review, enhancement

#4817 aio-interface: show timestamps next to log entries
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#4737 Docs: Update manual-upgrade.md with alternative method
  manual-upgrade.md
Labels: 3. to review, documentation

#4835 community-containers: Add NocoDB
  community-containers/caddy/readme.md
  community-containers/nocodb/nocodb.json
  community-containers/nocodb/readme.md
Labels: 3. to review, enhancement

#4840 nextcloud: print warning if login as root into container
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/root.motd
Labels: 3. to review, enhancement

#4851 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review, dependencies

#4856 database-restore: only get the first match
  Containers/postgresql/start.sh
Labels: 3. to review, bug

#4858 nextcloud: properly add REDIS_DB_INDEX
  Containers/nextcloud/config/redis.config.php
Labels: 3. to review, enhancement

#4859 imaginary: update alpine to 3.20
  Containers/imaginary/Dockerfile
Labels: 3. to review, dependencies

#4857 update alpine to v3.20.1
  Containers/apache/Dockerfile
  Containers/borgbackup/Dockerfile
  Containers/docker-socket-proxy/Dockerfile
  Containers/domaincheck/Dockerfile
  Containers/mastercontainer/Dockerfile
  Containers/nextcloud/Dockerfile
  Containers/notify-push/Dockerfile
  Containers/talk-recording/Dockerfile
  Containers/talk/Dockerfile
  Containers/watchtower/Dockerfile
  community-containers/dlna/dlna.json
  community-containers/dlna/readme.md
  nextcloud-aio-helm-chart/Chart.yaml
  nextcloud-aio-helm-chart/readme.md
  nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-persistentvolumeclaim.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-clamav-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-clamav-persistentvolumeclaim.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-clamav-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-collabora-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-collabora-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-database-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-database-dump-persistentvolumeclaim.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-database-persistentvolumeclaim.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-database-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-elasticsearch-persistentvolumeclaim.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-fulltextsearch-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-fulltextsearch-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-imaginary-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-imaginary-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-namespace-namespace.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-data-persistentvolumeclaim.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-persistentvolumeclaim.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-trusted-cacerts-persistentvolumeclaim.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-notify-push-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-notify-push-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-onlyoffice-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-onlyoffice-persistentvolumeclaim.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-onlyoffice-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-redis-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-redis-persistentvolumeclaim.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-redis-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-recording-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-recording-service.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-service.yaml
  nextcloud-aio-helm-chart/update-helm.sh
  nextcloud-aio-helm-chart/values.yaml
  readme.md
Labels: 3. to review, dependencies

#4860 docker-socket-proxy: update haproxy to v3
  Containers/docker-socket-proxy/Dockerfile
Labels: 3. to review, dependencies

#4876 collabora: add SYS_ADMIN cap
  php/containers.json
Labels: 3. to review, enhancement

#4883 readme: Add section `Securing the AIO interface from unauthorized ACME challenges`
  readme.md
Labels: 3. to review, documentation

#4886 nextcloud: increase to 29.0.3
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies

#4715 Add documentation not to use @ or : in passwords
  manual-install/readme.md
  nextcloud-aio-helm-chart/readme.md
  nextcloud-aio-helm-chart/values.yaml
Labels: 3. to review, documentation
