Repository nextcloud/all-in-one, pull requests merged in 2024-05, with the labels that each got.

#4617 fix(entrypoint): system config value types
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, bug

#4609 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
  php/src/Auth/AuthManager.php
  php/src/Controller/DockerController.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, dependencies

#4651 change the rewrite for remote.php
  Containers/apache/Caddyfile
Labels: 3. to review, bug

#4588 improve UX and UI
  php/public/automatic_reload.js
  php/public/domain-prefill.js
  php/public/style.css
  php/public/timezone.js
  php/templates/containers.twig
  php/templates/login.twig
  php/templates/setup.twig
Labels: 3. to review, design, enhancement

#4662 Update containers.twig
  php/templates/containers.twig
Labels: 3. to review, enhancement

#4433 Add a config option for the postgres database port
  Containers/nextcloud/entrypoint.sh
  Containers/nextcloud/healthcheck.sh
  Containers/nextcloud/start.sh
  Containers/notify-push/start.sh
  php/containers.json
Labels: 3. to review, enhancement

#4680 Corrects a typo in containers.twig
  php/templates/containers.twig
Labels: 3. to review, enhancement

#4274 Add information about virtual machines
  multiple-instances.md
Labels: 3. to review, documentation

#4685 fix limiting php-fpm socket to certain ip-addresses
  Containers/nextcloud/start.sh
Labels: 3. to review, bug

#4689 Revert "Bump collabora/code from 24.04.1.4.1 to 24.04.2.1.1 in /Containers/collabora"
  Containers/collabora/Dockerfile
Labels: 3. to review, bug, regression

#4690 fix collabora build by not running apt-get upgrade
  Containers/collabora/Dockerfile
Labels: 3. to review, bug

#4692 fix bug with getting api_version
  Containers/mastercontainer/start.sh
Labels: 3. to review, bug

#4693 add borg_backup_mode to Backup container status
  php/templates/containers.twig
Labels: 3. to review, enhancement

#4696 adjust apache reverse proxy docs to set x-real-ip
  reverse-proxy.md
Labels: 3. to review, documentation

#4708 AIO interface: substitute `b` tag with `strong` tag
  php/templates/containers.twig
  php/templates/includes/aio-config.twig
  php/templates/includes/backup-dirs.twig
  php/templates/login.twig
  php/templates/setup.twig
Labels: 3. to review, enhancement

#4707 AIO interface: document limitation regarding restoring of community container data
  php/templates/containers.twig
Labels: 3. to review, enhancement

#4706 apache: remove caddy-imports
  Containers/apache/Caddyfile
  Containers/apache/start.sh
Labels: 3. to review, enhancement

#4709 AIO interface: add note how to reset the AIO instance
  multiple-instances.md
  php/templates/containers.twig
Labels: 3. to review, enhancement

#4713 Revert "Revert "apache - drop SetEnv proxy-sendcl 1""
  Containers/apache/nextcloud.conf
Labels: 3. to review, enhancement

#4556 Update stalwart.json - add port definition for web admin interface
  community-containers/stalwart/readme.md
  community-containers/stalwart/stalwart.json
  community-containers/stalwart/upgrading.md
Labels: 2. developing, enhancement

#4723 helm: allow to set default quota for Nextcloud
  Containers/nextcloud/entrypoint.sh
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
  nextcloud-aio-helm-chart/update-helm.sh
  nextcloud-aio-helm-chart/values.yaml
Labels: 3. to review, enhancement

#4728 nextcloud: wait for redis to start
  Containers/nextcloud/entrypoint.sh
  Containers/redis/start.sh
Labels: 3. to review, enhancement

#4741 Fix record type for caddy-stalwart
  community-containers/caddy/readme.md
Labels: 3. to review, documentation
