Repository nextcloud/all-in-one, pull requests merged in 2024-07, with the labels that each got.

#4939 Correct wording in containers.twig
  php/templates/containers.twig
Labels: 3. to review, enhancement

#4957 Update reverse-proxy.md
  reverse-proxy.md
Labels: 3. to review, documentation

#4964 nextcloud: fix APPS_ALLOWLIST
  Containers/nextcloud/config/apps.config.php
Labels: 3. to review, bug

#4960 clamav - adjust max filesize conditionally
  Containers/clamav/Dockerfile
  Containers/clamav/clamav.conf
  Containers/clamav/start.sh
  Containers/nextcloud/entrypoint.sh
  php/containers.json
Labels: 3. to review, bug

#4971 get rid of "some font thing failed" error messages
  Containers/imaginary/Dockerfile
Labels: 3. to review, enhancement

#4976 update the ipv6 documentation
  compose.yaml
  docker-ipv6-support.md
  manual-install/latest.yml
  manual-install/sample.conf
  manual-install/update-yaml.sh
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, documentation

#4988 helm: allow to disable creation of namespace
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, enhancement

#4996 update-helm: adjust workflow for new tags syntax
  .github/workflows/update-helm.yml
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, enhancement

#4973 fix: remove unused go binaries from redis and postgresql images
  Containers/apache/Dockerfile
  Containers/postgresql/Dockerfile
  Containers/redis/Dockerfile
Labels: 3. to review, enhancement

#4981 caddy community-container: allow to disable the vaultwarden admin interface
  community-containers/caddy/caddy.json
  community-containers/vaultwarden/readme.md
Labels: 3. to review, enhancement

#4671 Add note to get correct source IP when using rootless docker
  docker-rootless.md
Labels: 3. to review, documentation

#5024 helm: add network policy
  nextcloud-aio-helm-chart/templates/nextcloud-aio-networkpolicy.yaml
  nextcloud-aio-helm-chart/update-helm.sh
  nextcloud-aio-helm-chart/values.yaml
Labels: 3. to review, enhancement

#5046 nextcloud: allow to skip database optimization
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#5044 helm: allow to set NEXTCLOUD_MAINTENANCE_WINDOW
  Containers/nextcloud/entrypoint.sh
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, enhancement

#5040 Improve the development environment
  .github/workflows/php-deprecation-detector.yml
  .github/workflows/psalm-update-baseline.yml
  .github/workflows/psalm.yml
  .github/workflows/twig-lint.yml
  .gitignore
  Containers/mastercontainer/.idea/.gitignore
  Containers/mastercontainer/.idea/mastercontainer.iml
  Containers/mastercontainer/.idea/misc.xml
  Containers/mastercontainer/.idea/modules.xml
  Containers/mastercontainer/.idea/vcs.xml
  php/.gitignore
  php/.idea/.gitignore
  php/.idea/aio.iml
  php/.idea/modules.xml
  php/.idea/php.xml
  php/.idea/vcs.xml
  php/README.md
  php/composer.json
  php/composer.lock
Labels: 3. to review, enhancement

#5071 RP-docs: Apache: increase timeout to support big file uploads
  reverse-proxy.md
Labels: 3. to review, documentation
