Repository nextcloud/all-in-one, pull requests merged in 2024-10, with the labels that each got.

#5348 docs: update readme.md
  readme.md
Labels: 3. to review, documentation

#5353 Use GitHub Markdown boxes in readme
  readme.md
Labels: 3. to review, documentation

#5354 Revert "Update containers.json to fix inter-container-connectivity"
  php/containers.json
Labels: 3. to review, enhancement

#5371 Add docker in readme
  php/README.md
Labels: 3. to review, documentation

#5374 Readme: update instructions for cifs mounts
  readme.md
Labels: 3. to review, documentation

#5369 aio-interface: Improve psalm
  php/README.md
  php/composer.json
  php/psalm.xml
Labels: 3. to review, enhancement

#5373 fix(pecl): configuration options in the right order
  .github/workflows/nextcloud-update.yml
  Containers/nextcloud/Dockerfile
Labels: 3. to review, bug

#5379 aio-interface: invalidate cache of options-form-submit.js
  php/templates/containers.twig
Labels: 3. to review, bug

#5389 Inprove constructor
  php/src/Auth/AuthManager.php
  php/src/Container/Container.php
  php/src/Container/ContainerPort.php
  php/src/Container/ContainerVolume.php
  php/src/ContainerDefinitionFetcher.php
  php/src/Controller/ConfigurationController.php
  php/src/Controller/DockerController.php
  php/src/Controller/LoginController.php
  php/src/Data/Setup.php
  php/src/Docker/DockerActionManager.php
  php/src/Docker/DockerHubManager.php
  php/src/Middleware/AuthMiddleware.php
  php/src/Twig/CsrfExtension.php
Labels: 3. to review, enhancement

#5372 Use enum instead of interface for state
  php/src/Container/Container.php
  php/src/Container/ContainerState.php
  php/src/Container/State/IContainerState.php
  php/src/Container/State/ImageDoesNotExistState.php
  php/src/Container/State/NotRestartingState.php
  php/src/Container/State/RestartingState.php
  php/src/Container/State/RunningState.php
  php/src/Container/State/StartingState.php
  php/src/Container/State/StoppedState.php
  php/src/Container/State/VersionDifferentState.php
  php/src/Container/State/VersionEqualState.php
  php/src/Container/VersionState.php
  php/src/ContainerDefinitionFetcher.php
  php/src/Controller/DockerController.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#5398 nginx: adjust configs
  reverse-proxy.md
Labels: 3. to review, documentation

#5241 Update reverse-proxy.md
  reverse-proxy.md
Labels: 3. to review, documentation

#5397 feat(ui): introducing dark-mode and refactor some templates and css
  php/public/img/Background_Light.jpg
  php/public/img/jenna-kim-the-globe-dark.webp
  php/public/img/jenna-kim-the-globe.webp
  php/public/img/logo-blue.svg
  php/public/img/logo.svg
  php/public/img/nextcloud-logo.svg
  php/public/style.css
  php/public/toggle-dark-mode.js
  php/templates/already-installed.twig
  php/templates/containers.twig
  php/templates/layout.twig
  php/templates/login.twig
  php/templates/setup.twig
Labels: 3. to review, design, enhancement

#5434 aio-interface: fix dark-mode
  php/public/style.css
  php/public/toggle-dark-mode.js
  php/templates/containers.twig
  php/templates/layout.twig
  php/templates/login.twig
Labels: 3. to review, bug

#5409 [reverse-proxy.md] Add Tailscale integration setup
  reverse-proxy.md
Labels: 3. to review, documentation

#5440 rp-docs: add links to examples direclty to each rp section
  local-instance.md
  reverse-proxy.md
Labels: 3. to review, documentation

#5460 readme: add tailscale network instructions
  readme.md
Labels: 3. to review, documentation

#5459 Refactor manual-install Compose.yml: Simplify Environment Variables
  manual-install/latest.yml
  manual-install/update-yaml.sh
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, enhancement

#5470 compose.yaml: document additional available envs
  compose.yaml
Labels: 3. to review, documentation

#5476 refactor compose.yaml: adjust the caddy setup to feature inline config
  compose.yaml
Labels: 3. to review, documentation

#5481 aio-interface: fix dark-mode and checkbox style
  php/public/style.css
  php/public/toggle-dark-mode.js
  php/templates/layout.twig
Labels: 3. to review, bug

#5473 Update readme.md local documentation
  local-instance.md
  readme.md
Labels: 2. developing, documentation

#5497 nextcloud: clean up old sessions after 24h latest
  Containers/nextcloud/Dockerfile
Labels: 3. to review, enhancement

#5495 elastic container: ingest-attachment is now module and not a plugin
  Containers/fulltextsearch/Dockerfile
Labels: 3. to review, enhancement

#5500 npmplus: Update readme.md
  community-containers/npmplus/readme.md
Labels: 3. to review, documentation

#5499 Update docker-rootless.md - missprint + improvement
  docker-rootless.md
Labels: 3. to review, documentation
