Repository nextcloud/all-in-one, pull requests merged in 2024-03, with the labels that each got.

#4293 Fix and beautify link to Docker --init
  readme.md
Labels: 3. to review, documentation

#4279 Added a replace statement for the database-dump.sql
  migration.md
Labels: 3. to review, documentation

#4116 Drop NET_RAW from all containers in manual
  manual-install/latest.yml
  php/containers-schema.json
  php/containers.json
Labels: 3. to review, enhancement

#4302 Fixed replace statement
  migration.md
Labels: 3. to review, documentation

#4312 helm chart - adjust strategy to recreate
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, enhancement

#4316 increase version of aio app
  app/appinfo/info.xml
Labels: 3. to review, enhancement

#4318 update mastercontainer to php8.3
  .github/workflows/dependency-updates.yml
  .github/workflows/lint-php.yml
  .github/workflows/php-deprecation-detector.yml
  .github/workflows/psalm-update-baseline.yml
  .github/workflows/psalm.yml
  .github/workflows/twig-lint.yml
  Containers/mastercontainer/Dockerfile
  php/composer.json
  php/composer.lock
Labels: 3. to review, dependencies

#4321 update Nextcloud to 28.0.3
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies

#4320 update nextcloud container to php8.2
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies

#4323 apache - drop SetEnv proxy-sendcl 1
  Containers/apache/nextcloud.conf
Labels: 3. to review, enhancement

#4324 nextcloud - set maintenance_window_start
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#4325 secure imaginary with imaginary_key
  Containers/imaginary/Dockerfile
  Containers/imaginary/start.sh
  Containers/nextcloud/entrypoint.sh
  php/containers.json
Labels: 3. to review, enhancement

#4314 helm - only add namespace if it is not default
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, enhancement

#4326 caddy community container - allow to access host.docker.internal
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#4267 Add a jellyfin community-container
  community-containers/caddy/readme.md
  community-containers/jellyfin/jellyfin.json
  community-containers/jellyfin/readme.md
  community-containers/plex/readme.md
Labels: 3. to review, enhancement

#3906 [breaking] - update aio-local-ai to v2
  community-containers/local-ai/local-ai.json
  community-containers/local-ai/readme.md
Labels: 3. to review, enhancement, dependencies

#4332 Add informations about custom caddy rules.
  community-containers/caddy/readme.md
Labels: 3. to review, documentation

#4334 Add note ncadmin is a temporary PostgreSQL user
  migration.md
Labels: 3. to review, documentation

#4343 Disable Apache proxy buffering
  Containers/apache/nextcloud.conf
Labels: 3. to review, enhancement

#4358 Make more clear that port 8080 needs to be accessed via ip-address
  Containers/mastercontainer/start.sh
  readme.md
  reverse-proxy.md
Labels: 3. to review, documentation, enhancement

#4387 Helm chart - Add private mirror support for OCI
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, enhancement

#4411 Additonal backup paths - fix regex
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, bug

#4408 log the whole error message when network creation fails
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#4386 nextcloud - update apps_paths to include absolute path
  Containers/nextcloud/config/apps.config.php
Labels: 3. to review, enhancement

#4357 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review, dependencies

#4399 aio interface - adjust wording for disable daily backups button
  php/templates/containers.twig
Labels: 3. to review, enhancement

#4347 chore: update workflows from templates
  .github/workflows/lint-php.yml
  .github/workflows/psalm.yml
Labels: 3. to review, dependencies, automated

#4429 Fixed a typo in containers.twig
  php/templates/containers.twig
Labels: 3. to review, enhancement

#4447 fix(helm): image repo transformation yielding invalid yaml string syntax
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, bug

#4450 run helm lint to catch any problems
  .github/workflows/helm-release.yml
Labels: 3. to review, enhancement

#4451 ci(lint-helm): simplify workflow
  .github/workflows/lint-helm.yml
Labels: 3. to review, dependencies

#4448 update helm chart
  nextcloud-aio-helm-chart/Chart.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-clamav-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-collabora-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-database-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-fulltextsearch-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-imaginary-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-notify-push-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-onlyoffice-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-redis-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-recording-deployment.yaml
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, dependencies

#4459 nextcloud container - add redis session handler to Dockerfile
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement
