Repository nextcloud/all-in-one, pull requests merged in 2024-02, with the labels that each got.

#4147 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review, dependencies

#4142 update all remaining images to alpine3.19
  Containers/apache/Dockerfile
  Containers/docker-socket-proxy/Dockerfile
  Containers/imaginary/Dockerfile
  Containers/mastercontainer/Dockerfile
  Containers/nextcloud/Dockerfile
  Containers/talk-recording/Dockerfile
  readme.md
Labels: 3. to review, dependencies

#4151 helm chart - allow to add additional trusted domain
  Containers/apache/Caddyfile
  Containers/apache/start.sh
  Containers/nextcloud/entrypoint.sh
  nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
  nextcloud-aio-helm-chart/update-helm.sh
  nextcloud-aio-helm-chart/values.yaml
Labels: 3. to review, enhancement

#4168 fix imagick not having svg support
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/start.sh
Labels: 3. to review, bug

#4219 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review, dependencies

#4210 hider server and x-powered-by header
  Containers/apache/Caddyfile
Labels: 3. to review, enhancement

#4227 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review, dependencies

#4232 add syntax=docker/dockerfile:latest
  Containers/apache/Dockerfile
  Containers/borgbackup/Dockerfile
  Containers/clamav/Dockerfile
  Containers/collabora/Dockerfile
  Containers/docker-socket-proxy/Dockerfile
  Containers/domaincheck/Dockerfile
  Containers/fulltextsearch/Dockerfile
  Containers/imaginary/Dockerfile
  Containers/mastercontainer/Dockerfile
  Containers/nextcloud/Dockerfile
  Containers/notify-push/Dockerfile
  Containers/onlyoffice/Dockerfile
  Containers/postgresql/Dockerfile
  Containers/redis/Dockerfile
  Containers/talk-recording/Dockerfile
  Containers/talk/Dockerfile
  Containers/watchtower/Dockerfile
Labels: 3. to review, enhancement

#4235 Fix pi-hole dashboard page url
  community-containers/pi-hole/readme.md
Labels: 3. to review, documentation

#4234 Add extra informations about root-data change for Docker
  readme.md
Labels: 3. to review, documentation

#4249 fix: Do not apply an empty allow list if none is set
  Containers/nextcloud/config/apps.config.php
Labels: 3. to review, bug

#4254 log the whole exception if container could not be started
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#4256 harden pulling images from docker hub issues
  php/src/Controller/DockerController.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#4253 revert imaginary container to alpine3.18
  Containers/imaginary/Dockerfile
Labels: 3. to review, bug

#4270 helm chart - disable FTS volume if not enabled
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, enhancement

#4268 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review, dependencies

#4292 nextcloud entrypoint - move /usr/src/nextcloud to SOURCE_LOCATION
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement
