Repository nextcloud/all-in-one, pull requests merged in 2024-04, with the labels that each got.

#4285 Add a clarifying comment to nginx.conf of reverse-proxy.md
  reverse-proxy.md
Labels: 3. to review, documentation

#4398 Add lldap comunity container
  community-containers/caddy/readme.md
  community-containers/lldap/lldap.json
  community-containers/lldap/readme.md
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#4492 helm chart - allow to adjust TALK_MAX_STREAM_BITRATE
  Containers/talk/start.sh
  nextcloud-aio-helm-chart/Chart.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-deployment.yaml
  nextcloud-aio-helm-chart/update-helm.sh
  nextcloud-aio-helm-chart/values.yaml
Labels: 3. to review, enhancement

#4495 nextcloud - adjust TALK_HOST logic
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#4513 feat: enable HEIC+TIFF without Imaginary
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/start.sh
Labels: 3. to review, enhancement

#4523 nextcloud container - add exit to cronjob
  Containers/nextcloud/cron.sh
Labels: 3. to review, bug

#4530 improve the change domain documentation
  readme.md
Labels: 3. to review, documentation

#4533 helm chart - allow to adjust TALK_MAX_SCREEN_BITRATE
  Containers/talk/start.sh
  nextcloud-aio-helm-chart/Chart.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-deployment.yaml
  nextcloud-aio-helm-chart/update-helm.sh
  nextcloud-aio-helm-chart/values.yaml
Labels: 3. to review, enhancement

#4532 nextcloud - add logic for BRUTEFORCE_PROTECTION
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#4550 aio interface - show upgrade hint for 29
  php/src/Controller/DockerController.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#4572 allow logs endpoint in haproxy.cfg for docker-socket-proxy
  Containers/docker-socket-proxy/haproxy.cfg
Labels: 3. to review, enhancement

#4559 upgrade preinstalled packages in final build step
  .gitattributes
  Containers/apache/Dockerfile
  Containers/borgbackup/Dockerfile
  Containers/clamav/Dockerfile
  Containers/collabora/Dockerfile
  Containers/docker-socket-proxy/Dockerfile
  Containers/domaincheck/Dockerfile
  Containers/fulltextsearch/Dockerfile
  Containers/imaginary/Dockerfile
  Containers/mastercontainer/Dockerfile
  Containers/nextcloud/Dockerfile
  Containers/notify-push/Dockerfile
  Containers/postgresql/Dockerfile
  Containers/redis/Dockerfile
  Containers/talk-recording/Dockerfile
  Containers/talk/Dockerfile
  Containers/watchtower/Dockerfile
Labels: 3. to review, enhancement

#4586 Revert "apache - drop SetEnv proxy-sendcl 1"
  Containers/apache/nextcloud.conf
Labels: 3. to review, bug

#4560 trust IP of docker network gateway
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#4587 adjust the compose file to use `:` instead of `=`
  compose.yaml
Labels: 3. to review, enhancement

#4589 compose file: Correct the mix of two syntaxes in environment variables
  compose.yaml
Labels: 3. to review, enhancement

#4593 nginx config should also work for freenginx and openresty
  reverse-proxy.md
Labels: 3. to review, documentation

#4571 LLDAP - Update ReadMe
  community-containers/lldap/readme.md
Labels: 3. to review, documentation
