Repository nextcloud/all-in-one, pull requests merged in 2024-08, with the labels that each got.

#5078 daily-backup: fix issue with APACHE_PORT
  Containers/mastercontainer/daily-backup.sh
Labels: 3. to review, bug, regression

#5085 manual-install: adjust the docker-compose commands
  manual-install/readme.md
Labels: 3. to review, documentation

#5089 readme: fix mistakes in Cloudflare section
  readme.md
Labels: 3. to review, documentation

#5092 Added reverse proxy configuration example for IIS with ARR & Url Rewrite
  reverse-proxy.md
Labels: 3. to review, documentation

#5106 nextcloud: improve update logic
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#5016 Refactor the frontend
  php/public/style.css
  php/templates/containers.twig
  php/templates/includes/aio-config.twig
  php/templates/includes/backup-dirs.twig
  php/templates/login.twig
  php/templates/setup.twig
Labels: 3. to review, enhancement

#5093 nextcloud: allow to configure proxy options via env
  Containers/nextcloud/config/proxy.config.php
Labels: 3. to review, enhancement

#5117 nextcloud: config files: do not compare against false
  Containers/nextcloud/config/apps.config.php
  Containers/nextcloud/config/proxy.config.php
  Containers/nextcloud/config/redis.config.php
Labels: 3. to review, enhancement

#5136 helm-chart: fix ALPINE_IMAGE_ORG variable
  nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-clamav-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-database-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-fulltextsearch-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-notify-push-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-onlyoffice-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-redis-deployment.yaml
  nextcloud-aio-helm-chart/update-helm.sh
  nextcloud-aio-helm-chart/values.yaml
Labels: 3. to review, bug

#5007 aio-interface: adjust design for nc30
  php/public/img/Background_Light.jpg
  php/public/img/background.png
  php/public/style.css
Labels: 3. to review, design, enhancement

#5139 Update Stalwart doc
  community-containers/stalwart/readme.md
  community-containers/stalwart/upgrading.md
Labels: 3. to review, documentation

#5175 mastercontainer: add warning if snap install was found
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#5126 adjust redis connector to point at correct db-index
  Containers/nextcloud/Dockerfile
  Containers/notify-push/start.sh
Labels: 3. to review, enhancement
