Repository nextcloud/all-in-one, pull requests merged in 2024-11, with the labels that each got.

#5505 Update truenas scale section in readme.md
  readme.md
Labels: 3. to review, documentation

#5519 helm: update network policy
  nextcloud-aio-helm-chart/templates/nextcloud-aio-networkpolicy.yaml
  nextcloud-aio-helm-chart/update-helm.sh
  nextcloud-aio-helm-chart/values.yaml
Labels: 3. to review, enhancement

#5520 helm: add additional security settings
  nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-clamav-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-collabora-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-database-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-fulltextsearch-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-imaginary-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-notify-push-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-redis-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-recording-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-whiteboard-deployment.yaml
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, enhancement

#5510 Fix twig
  php/templates/already-installed.twig
  php/templates/login.twig
  php/templates/setup.twig
Labels: 3. to review, bug

#5507 aio-interface: add debug docs to collabora, talk and fts
  .github/workflows/json-validator.yml
  php/containers.json
Labels: 3. to review, enhancement

#5503 DockerActionManager: fix getting the tag from the image
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, bug

#5527 nextcloud: add libreoffice by default
  Containers/nextcloud/Dockerfile
  readme.md
Labels: 3. to review, enhancement

#5528 add user-IDs to all containers
  .github/workflows/json-validator.yml
  Containers/apache/Dockerfile
  Containers/clamav/Dockerfile
  Containers/imaginary/Dockerfile
  Containers/postgresql/Dockerfile
  Containers/redis/Dockerfile
  Containers/talk-recording/Dockerfile
  Containers/talk/Dockerfile
  Containers/whiteboard/Dockerfile
  manual-install/latest.yml
  manual-install/update-yaml.sh
  php/containers-schema.json
  php/containers.json
Labels: 3. to review, enhancement

#5530 user must be a string
  .github/workflows/json-validator.yml
  manual-install/latest.yml
  php/containers-schema.json
  php/containers.json
Labels: 3. to review, bug

#5532 ci(json-validator): use venv
  .github/workflows/json-validator.yml
Labels: 3. to review, dependencies

#5535 readme reset instance guide typo
  readme.md
Labels: 3. to review, documentation

#5484 Specifying additional docker network for Apache container
  Containers/mastercontainer/start.sh
  compose.yaml
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  reverse-proxy.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#5536 nextcloud: update to 29.0.9
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies

#5537 talk-recording: change to firefox-esr
  Containers/talk-recording/Dockerfile
Labels: 3. to review, bug

#5538 talk-recording: change tmpfs to volume
  Containers/talk-recording/Dockerfile
  Containers/talk-recording/start.sh
  php/containers.json
Labels: 3. to review, bug

#5543 Revert "talk-recording: change to firefox-esr"
  Containers/talk-recording/Dockerfile
Labels: 3. to review, bug

#4804 Add remote borg backup support
  Containers/borgbackup/Dockerfile
  Containers/borgbackup/backupscript.sh
  Containers/borgbackup/borg_excludes
  Containers/borgbackup/start.sh
  php/containers.json
  php/public/index.php
  php/src/Controller/ConfigurationController.php
  php/src/Data/ConfigurationManager.php
  php/src/Data/DataConst.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
  readme.md
Labels: 3. to review, enhancement, borg

#5314 helm: adjust initcontainer: use fixed alpine tag
  nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-clamav-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-database-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-fulltextsearch-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-notify-push-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-onlyoffice-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-redis-deployment.yaml
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, enhancement

#5426 nextcloud: add `documentation_url.server_logs`
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#5549 helm: remove IMAGE_MIRROR_PREFIX, NEXTCLOUD_IMAGE_ORG and ALPINE_IMAGE_ORG
  nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-clamav-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-collabora-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-database-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-fulltextsearch-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-imaginary-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-notify-push-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-onlyoffice-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-redis-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-recording-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-whiteboard-deployment.yaml
  nextcloud-aio-helm-chart/update-helm.sh
  nextcloud-aio-helm-chart/values.yaml
Labels: 3. to review, enhancement

#5548 aio-interface: remove hint regarding nc 30 update
  php/templates/containers.twig
Labels: 3. to review, enhancement

#5547 nextcloud-aio-app: increase to v0.7.0
  app/appinfo/info.xml
Labels: 3. to review, dependencies

#5551 nextcloud: upgrade to 30.0.2
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies

#5554 notify-scripts: add object type and object id
  Containers/nextcloud/notify-all.sh
  Containers/nextcloud/notify.sh
Labels: 3. to review, enhancement

#5553 borgbackup: make logs a bit cleaner if local archive is used
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, bug, borg

#5558 Correctly disable some supervisord logs
  Containers/apache/supervisord.conf
  Containers/mastercontainer/supervisord.conf
Labels: 3. to review, enhancement

#5573 aio-interface: fix small detail in `Reset backup location` section
  php/templates/containers.twig
Labels: 3. to review, bug

#5550 allow to exclude previews from restore upon instance restore
  Containers/borgbackup/backupscript.sh
  Containers/nextcloud/entrypoint.sh
  php/containers.json
  php/src/Controller/DockerController.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
Labels: 3. to review, enhancement, borg

#5576 feat: toggle submit button based on unsaved changes
  php/public/options-form-submit.js
  php/templates/containers.twig
  php/templates/includes/optional-containers.twig
Labels: 3. to review, enhancement, technical debt

#5575 build(nextcloud): bump php to 8.3
  .github/workflows/nextcloud-update.yml
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies

#5603 Update local-ai readme.md
  community-containers/local-ai/readme.md
Labels: 3. to review, documentation

#5590 borgbackup: improve testing backup upon instance restore
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, enhancement

#5591 Fix some typos.
  Containers/mastercontainer/start.sh
  compose.yaml
  php/templates/includes/aio-config.twig
Labels: 3. to review, enhancement

#5622 docker-socket-proxy: allowed read/write/exec of files for AppAPI for ExApps containers
  Containers/docker-socket-proxy/haproxy.cfg
Labels: 3. to review, enhancement

#5613 change default upload limit to 16G as recommended in the docs
  Containers/clamav/clamav.conf
  Containers/clamav/start.script
  Containers/nextcloud/Dockerfile
  compose.yaml
  manual-install/sample.conf
  manual-install/update-yaml.sh
  nextcloud-aio-helm-chart/update-helm.sh
  nextcloud-aio-helm-chart/values.yaml
  php/src/Data/ConfigurationManager.php
  readme.md
Labels: 3. to review, enhancement

#5601 helm: refactor securityContext
  manual-install/latest.yml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-clamav-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-collabora-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-database-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-fulltextsearch-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-imaginary-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-notify-push-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-onlyoffice-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-redis-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-recording-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-whiteboard-deployment.yaml
  nextcloud-aio-helm-chart/update-helm.sh
  php/containers.json
Labels: 3. to review, enhancement

#5662 helm: add a default for RPSS_ENABLED
  nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-clamav-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-database-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-imaginary-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-notify-push-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-redis-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-recording-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-whiteboard-deployment.yaml
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, bug

#5664 Revert "helm: add a default for RPSS_ENABLED"
  nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-clamav-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-database-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-imaginary-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-notify-push-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-redis-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-recording-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-whiteboard-deployment.yaml
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, bug

#5657 Document the user limit
  readme.md
Labels: 3. to review, documentation

#5666 manual-install: add back the nextcloud-aio network
  manual-install/latest.yml
  manual-install/update-yaml.sh
Labels: 3. to review, bug

#5668 Revert "manual-install: add back the nextcloud-aio network"
  manual-install/latest.yml
  manual-install/update-yaml.sh
Labels: 3. to review, bug
