Repository nextcloud/all-in-one, pull requests merged in 2025-08, with the labels that each got.

#6732 fix shellcheck
  Containers/mastercontainer/start.sh
  Containers/nextcloud/entrypoint.sh
  Containers/watchtower/start.sh
Labels: 3. to review, enhancement

#6736 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review, dependencies

#6778 readme: docs for moving install to different drive: use force to prune docker resources
  readme.md
Labels: 3. to review, documentation

#6770 stalwart: add support for ClamAV
  community-containers/stalwart/stalwart.json
Labels: 4. to release, enhancement

#6777 collabora: add further caps
  php/containers.json
Labels: 3. to review, enhancement

#6798 clamav: set permissions for `/var/lib/clamav` correctly
  Containers/clamav/Dockerfile
Labels: 3. to review, enhancement

#6779 Add docs how to adjust MTU size of the docker network
  compose.yaml
  readme.md
Labels: 3. to review, enhancement
