Repository nextcloud/all-in-one, pull requests merged in 2025-04, with the labels that each got.

#6259 libretranslate-cc: add warning that it is deprecated
  community-containers/libretranslate/readme.md
Labels: 3. to review, documentation

#6255 mastercontainer: improve check for ghcr.io
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#6275 daily-backup.sh: connect mastercontainer to nextcloud-aio network
  Containers/mastercontainer/daily-backup.sh
Labels: 3. to review, enhancement

#6278 aio-interface: daily-backup: remove the pre-filled value
  php/templates/containers.twig
Labels: 3. to review, enhancement

#6279 aio-interface: describe that the submit button needs to be pressed in a few places
  php/templates/containers.twig
  php/templates/includes/optional-containers.twig
Labels: 3. to review, enhancement

#6282 nextcloud: update to 30.0.9
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies

#6308 feat(docker-socket-proxy): allow inspect image rule
  Containers/docker-socket-proxy/haproxy.cfg
Labels: 3. to review, enhancement

#6312 nextcloud: update imagick to 3.8.0 and revert imagick workaround
  .github/workflows/nextcloud-update.yml
  Containers/nextcloud/Dockerfile
Labels: 3. to review, enhancement

#6311 Docker-socket-proxy: Update haproxy.cfg to fix timeouts
  Containers/docker-socket-proxy/haproxy.cfg
Labels: 3. to review, bug

#6348 manual-upgrade: adjust the docs to mention docker hub as well
  manual-upgrade.md
Labels: 3. to review, documentation

#6351 mastercontainer: update to php8.4
  .github/workflows/dependency-updates.yml
  .github/workflows/lint-php.yml
  .github/workflows/php-deprecation-detector.yml
  .github/workflows/psalm-update-baseline.yml
  .github/workflows/psalm.yml
  .github/workflows/twig-lint.yml
  Containers/mastercontainer/Dockerfile
  php/composer.json
  php/composer.lock
  php/psalm-baseline.xml
  php/psalm.xml
Labels: 3. to review, dependencies

#6354 Revert "borgbackup: always use the progress option when creating an archive"
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, enhancement, borg
