Repository nextcloud/all-in-one, pull requests merged in 2025-07, with the labels that each got.

#6597 Revert "build(deps): bump onlyoffice/documentserver from 8.3.3.1 to 9.0.2.1 in /Containers/onlyoffice"
  Containers/onlyoffice/Dockerfile
Labels: 3. to review

#6522 add container-management cc
  community-containers/caddy/readme.md
  community-containers/container-management/container-management.json
  community-containers/container-management/readme.md
  community-containers/facerecognition/readme.md
  community-containers/fail2ban/readme.md
  community-containers/lldap/readme.md
  community-containers/npmplus/readme.md
  community-containers/readme.md
  readme.md
Labels: 3. to review, enhancement

#6638 mastercontainer: add mountpoint check for `/var/www/docker-aio/php/containers.json`
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#6612 collabora: change startup logs from trace to warning
  php/containers.json
Labels: 3. to review, enhancement

#6617 db-import: improve the import process by using the `smart` mode and a higher timeout
  Containers/postgresql/start.sh
Labels: 3. to review, enhancement

#6631 CreateContainer: Also add `diun.enable: false` to all managed containers
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#6644 mastercontainer: add advice to `/var/www/docker-aio/php/containers.json` mountpoint warning
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#6667 update remaining images and docs to alpine v3.22
  Containers/apache/Dockerfile
  Containers/imaginary/Dockerfile
  Containers/mastercontainer/Dockerfile
  Containers/nextcloud/Dockerfile
  Containers/postgresql/Dockerfile
  Containers/talk-recording/Dockerfile
  readme.md
Labels: 3. to review, dependencies

#6656 aio-interface: add hint to UI about SSH pubkey for remote backups
  php/templates/containers.twig
Labels: 3. to review, enhancement

#6682 PerformRecursiveContainerStop: Fix the stop order
  php/containers.json
  php/src/Controller/DockerController.php
Labels: 3. to review, bug

#6685 daily-backup: implement a dedicated imagepull before stopping containers which should reduce the downtime
  Containers/mastercontainer/daily-backup.sh
  php/src/Controller/DockerController.php
  php/src/Cron/PullContainerImages.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#6694 improve debugging of playwright.yml
  .github/workflows/playwright.yml
Labels: 3. to review, enhancement, technical debt
