Repository nextcloud/all-in-one, pull requests merged in 2025-01, with the labels that each got.

#5813 reverse-proxy-docu: adjust and add introduction with example
  reverse-proxy.md
Labels: 3. to review, documentation

#5785 nextcloud: set max opcache files to 1000
  Containers/nextcloud/Dockerfile
Labels: 3. to review, enhancement

#5786 Container.php: adjust casing of enable_nvidia_gpu to enableNvidiaGpu
  php/src/Container/Container.php
Labels: 3. to review, enhancement

#5792 Add "port" to borg remote placeholder
  php/templates/containers.twig
Labels: 4. to release, enhancement

#5820 facerecognition docker does not support GPU
  community-containers/facerecognition/facerecognition.json
Labels: 3. to review, enhancement

#5808 Updated IIS Reverse proxy configuration to work with special characters.
  reverse-proxy.md
Labels: 3. to review, documentation

#5803 local-ai-cc: disable nvidia-gpu as it disallows the container to start
  community-containers/local-ai/local-ai.json
Labels: 3. to review, bug

#5824 rename `ENABLE_NVIDIA_GPU` to `NEXTCLOUD_ENABLE_NVIDIA_GPU`
  compose.yaml
  php/src/Data/ConfigurationManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#5825 apache-healthcheck: remove the domain test
  Containers/apache/healthcheck.sh
Labels: 3. to review, enhancement

#5826 facerecognition: document fixed 1G value
  community-containers/facerecognition/readme.md
Labels: 3. to review, documentation

#5827 manual-install: document behaviour about exposed options
  manual-install/readme.md
Labels: 3. to review, documentation

#5828 nextcloud: check for configured appstoreurl during upgrade
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#5830 Adjust docs for talk_port variable a bit
  compose.yaml
  manual-install/update-yaml.sh
  readme.md
Labels: 3. to review, documentation

#5831 helm: remove NET_BIND_SERVICE if not needed
  nextcloud-aio-helm-chart/templates/nextcloud-aio-clamav-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-database-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-imaginary-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-notify-push-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-redis-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-talk-recording-deployment.yaml
  nextcloud-aio-helm-chart/templates/nextcloud-aio-whiteboard-deployment.yaml
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, enhancement

#5843 nextcloud-entrypoint: adjust logic around app api app
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#5861 domain-validation: improve the notice about the private ip-address
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, enhancement

#5862 containers-schema and containers.json: remove networks from definition
  php/containers-schema.json
  php/containers.json
Labels: 3. to review, enhancement

#5864 add calcardbackup community container
  community-containers/calcardbackup/calcardbackup.json
  community-containers/calcardbackup/readme.md
Labels: 3. to review, enhancement

#5870 allow to configure redis user
  Containers/nextcloud/Dockerfile
  Containers/nextcloud/config/redis.config.php
  Containers/notify-push/start.sh
  Containers/whiteboard/start.sh
Labels: 3. to review, enhancement

#5885 rp-docs: add info about hairpin-nat and local dns-record in debug section
  reverse-proxy.md
Labels: 3. to review, documentation

#5888 mastercontainer: check if auth.docker.io is reachable during startup
  Containers/mastercontainer/start.sh
  manual-install/readme.md
Labels: 3. to review, enhancement

#5881 fail2ban-cc: add jellyfin
  community-containers/fail2ban/fail2ban.json
  community-containers/fail2ban/readme.md
  community-containers/jellyfin/readme.md
Labels: 3. to review, enhancement

#5909 Update NPMplus community container readme.md
  community-containers/npmplus/readme.md
Labels: 3. to review, documentation

#5910 Improve the readme by clarifying that the NC instance can be restored by the backup data
  readme.md
Labels: 3. to review, documentation

#5923 Update dependabot.yml
  .github/dependabot.yml
Labels: 3. to review, enhancement, dependencies

#5895 improve check for auth.docker.io
  Containers/mastercontainer/start.sh
Labels: 3. to review, enhancement

#5920 DockerActionManager and DockerController: improve the logging
  php/src/Controller/DockerController.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#5921 apache: add docs to aio interface
  php/containers.json
Labels: 3. to review, enhancement

#5927 aio-interface: update wording for entering the domain
  php/templates/containers.twig
Labels: 3. to review, enhancement

#5899 Support custom port for onlyoffice
  Containers/apache/Caddyfile
Labels: 3. to review, enhancement

#5889 add borgbackup-viewer community container
  community-containers/borgbackup-viewer/borgbackup-viewer.json
  community-containers/borgbackup-viewer/readme.md
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
  readme.md
Labels: 3. to review, enhancement

#4902 community-containers: add makemkv
  community-containers/makemkv/makemkv.json
  community-containers/makemkv/readme.md
  php/containers-schema.json
Labels: 3. to review, enhancement

#5929 add scrutiny community container
  community-containers/scrutiny/readme.md
  community-containers/scrutiny/scrutiny.json
  php/containers-schema.json
Labels: 3. to review, enhancement

#5936 talk: automatically bind ipv4 only if ipv6 is disabled
  Containers/talk/start.sh
Labels: 3. to review, enhancement

#5955 make Tailscale even more prominent
  compose.yaml
  local-instance.md
  php/templates/containers.twig
  readme.md
Labels: 3. to review, documentation

#5977 aio-interface: add note that talk-recording only works on x86
  php/src/Data/ConfigurationManager.php
  php/templates/includes/optional-containers.twig
Labels: 3. to review, enhancement

#5945 containers-schema: allow to specify ui-secret and show in aio interface
  community-containers/borgbackup-viewer/borgbackup-viewer.json
  community-containers/borgbackup-viewer/readme.md
  community-containers/lldap/lldap.json
  community-containers/lldap/readme.md
  community-containers/makemkv/makemkv.json
  community-containers/makemkv/readme.md
  community-containers/nocodb/nocodb.json
  community-containers/nocodb/readme.md
  community-containers/stalwart/stalwart.json
  manual-install/update-yaml.sh
  php/containers-schema.json
  php/src/Container/Container.php
  php/src/ContainerDefinitionFetcher.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#5983 whiteboard: add tmpfs in app as this seems to be required now
  php/containers.json
Labels: 3. to review, bug
