Repository nextcloud/all-in-one, pull requests merged in 2025-02, with the labels that each got.

#5997 jellyseerr-cc: Update readme.md
  community-containers/jellyseerr/readme.md
Labels: 3. to review, documentation

#6001 jellyseerr-cc: eliminate tini errors
  community-containers/jellyseerr/jellyseerr.json
Labels: 3. to review, bug

#5990 run-exec-commands.sh. adjust message when waiting for container
  Containers/nextcloud/run-exec-commands.sh
Labels: 3. to review, enhancement

#5998 also add ui-secret to pi-hole and vaultwarden
  community-containers/pi-hole/pi-hole.json
  community-containers/pi-hole/readme.md
  community-containers/vaultwarden/readme.md
  community-containers/vaultwarden/vaultwarden.json
Labels: 3. to review, enhancement

#6004 readme: add TOC
  readme.md
Labels: 3. to review, documentation

#6013 scrutiny-cc: improve documentation
  community-containers/scrutiny/readme.md
Labels: 3. to review, documentation

#6025 notify-push: add timezone to container
  php/containers.json
Labels: 3. to review, bug

#6026 manual-upgrade: add note that method 1 seems to be currently broken
  manual-upgrade.md
Labels: 3. to review, documentation

#6027 readme: add chapter how to adjust version and trashbin retention policy
  readme.md
Labels: 3. to review, documentation

#6005 FTS: allow to adjust the ES_JAVA_OPTS
  Containers/fulltextsearch/Dockerfile
  compose.yaml
  manual-install/latest.yml
  manual-install/sample.conf
  manual-install/update-yaml.sh
  nextcloud-aio-helm-chart/templates/nextcloud-aio-fulltextsearch-deployment.yaml
  nextcloud-aio-helm-chart/update-helm.sh
  nextcloud-aio-helm-chart/values.yaml
  php/containers.json
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  readme.md
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#6009 borg: allow to exclude datadir and preview folder from backup via `.noaiobackup` file
  Containers/borgbackup/backupscript.sh
  readme.md
Labels: 3. to review, enhancement, borg

#6022 Allow Jellyfin write access to NEXTCLOUD_MOUNT
  community-containers/jellyfin/jellyfin.json
Labels: 3. to review, enhancement

#6058 readme: re-order the faq section and add chapters
  readme.md
Labels: 3. to review, documentation

#6070 fix: `pihole/pihole@latest` Web Admin interface
  community-containers/pi-hole/pi-hole.json
Labels: 3. to review, bug

#6071 caddy-cc-readme: Add missing info about Jellyseerr
  community-containers/caddy/readme.md
Labels: 3. to review, documentation

#6060 aio-interface: adjust applicable links to always open in a new tab
  app/templates/admin.php
  php/templates/containers.twig
  php/templates/includes/aio-config.twig
  php/templates/includes/backup-dirs.twig
  php/templates/includes/optional-containers.twig
  php/templates/login.twig
  php/templates/setup.twig
Labels: 3. to review, enhancement

#6085 collabora: allow to configure additional options
  manual-install/latest.yml
  manual-install/sample.conf
  manual-install/update-yaml.sh
  nextcloud-aio-helm-chart/templates/nextcloud-aio-collabora-deployment.yaml
  nextcloud-aio-helm-chart/update-helm.sh
  nextcloud-aio-helm-chart/values.yaml
  php/public/index.php
  php/src/Controller/ConfigurationController.php
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
  php/templates/includes/optional-containers.twig
Labels: 3. to review, enhancement

#6101 Enable whiteboard by default
  php/src/Data/ConfigurationManager.php
Labels: 3. to review, enhancement

#6102 DockerActionManager: fix setting CMD options for collabora
  php/src/Data/ConfigurationManager.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, bug
