Repository nextcloud/all-in-one, pull requests merged in 2025-05, with the labels that each got.

#6338 nextcloud: restart netcat once a day to ensure that it stays reachable
  Containers/nextcloud/supervisord.conf
Labels: 3. to review, enhancement

#6361 rp-docs: OpenLiteSpeed Guide
  reverse-proxy.md
Labels: 3. to review, documentation

#6371 Revert "build(deps): bump collabora/code from 24.04.13.3.1 to 25.04.1.1.1 in /Containers/collabora"
  Containers/collabora/Dockerfile
Labels: 3. to review, dependencies

#6374 helm: automatically enforce RPSS if configured
  .github/workflows/update-helm.yml
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, enhancement

#6392 containers.json: always add chown cap to collabora
  php/containers.json
Labels: 3. to review, enhancement

#6396 talk-recording: add NC_PROTOCOL variable to separate from HPB_PROTOCOL
  Containers/talk-recording/Dockerfile
  Containers/talk-recording/start.sh
Labels: 3. to review, enhancement

#6409 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review, dependencies

#6423 add `org.label-schema.vendor="Nextcloud"` label to all containers
  Containers/alpine/Dockerfile
  Containers/apache/Dockerfile
  Containers/borgbackup/Dockerfile
  Containers/clamav/Dockerfile
  Containers/collabora/Dockerfile
  Containers/docker-socket-proxy/Dockerfile
  Containers/domaincheck/Dockerfile
  Containers/fulltextsearch/Dockerfile
  Containers/imaginary/Dockerfile
  Containers/mastercontainer/Dockerfile
  Containers/nextcloud/Dockerfile
  Containers/notify-push/Dockerfile
  Containers/onlyoffice/Dockerfile
  Containers/postgresql/Dockerfile
  Containers/redis/Dockerfile
  Containers/talk-recording/Dockerfile
  Containers/talk/Dockerfile
  Containers/watchtower/Dockerfile
  Containers/whiteboard/Dockerfile
Labels: 3. to review, enhancement

#6430 Fix broken link in readme.md
  readme.md
Labels: 3. to review, documentation

#6433 nextcloud: increase apc.shm_size to 64M to match the docker default shm-size
  Containers/nextcloud/Dockerfile
Labels: 3. to review, enhancement

#6184 database-import: update logic to consider wrong line endings
  Containers/postgresql/start.sh
Labels: 3. to review, enhancement

#6440 app: increase version to allow nc31
  app/appinfo/info.xml
Labels: 3. to review, dependencies

#6445 aio-interface: hide instructions for upgrading to nc31
  php/templates/containers.twig
Labels: 3. to review, enhancement

#6450 [Automated] Update psalm-baseline.xml
  php/psalm-baseline.xml
Labels: 3. to review, dependencies

#6451 readme: update docs regarding unothorized ACME challenges
  readme.md
Labels: 3. to review, documentation

#6458 clamav: move LocalSocket to `/tmp/clamd.sock`
  Containers/clamav/Dockerfile
Labels: 3. to review, enhancement

#6443 aio-interface: allow to manage the community containers via the AIO interface
  Containers/mastercontainer/start.sh
  community-containers/readme.md
  compose.yaml
  php/psalm-baseline.xml
  php/psalm.xml
  php/public/containers-form-submit.js
  php/public/index.php
  php/public/options-form-submit.js
  php/src/Container/CommunityContainer.php
  php/src/Controller/ConfigurationController.php
  php/src/Data/ConfigurationManager.php
  php/templates/containers.twig
  php/templates/includes/community-containers.twig
  php/templates/includes/optional-containers.twig
  tests/QA/060-environmental-variables.md
Labels: 3. to review, enhancement

#6469 nextcloud: adjust permissions
  Containers/nextcloud/Dockerfile
Labels: 3. to review, enhancement

#6473 fix showing community containers in the AIO interface and enabling or disabling them
  php/src/Container/CommunityContainer.php
  php/src/Controller/ConfigurationController.php
  php/src/Data/ConfigurationManager.php
  php/templates/includes/community-containers.twig
Labels: 3. to review, bug
