Repository nextcloud/all-in-one, pull requests merged in 2025-06, with the labels that each got.

#6500 aio-interface: disable talk-recording correctly
  php/templates/containers.twig
Labels: 3. to review, bug, high

#6524 DockerController: avoid php warning when id not in query string in GetLogs Route
  php/src/Controller/DockerController.php
Labels: 3. to review, enhancement

#6551 entrypoint.sh: add additional logic for ONLYOFFICE_HOST
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#6585 readme: add "do not install Docker as snap"
  readme.md
Labels: 3. to review, documentation
