Repository nextcloud/all-in-one, pull requests merged in 2025-09, with the labels that each got.

#6818 update docs with new tailscale guide
  compose.yaml
  local-instance.md
  php/templates/containers.twig
  readme.md
  reverse-proxy.md
Labels: 3. to review, documentation

#6835 facerecognition-cc: update json to use actual secret for api key
  community-containers/facerecognition/facerecognition.json
Labels: 3. to review, enhancement

#6845 aio-interface setup page: fall back to system fonts if monospace does not exist
  php/public/style.css
Labels: 3. to review, enhancement

#6628 rp-docs: increase Treafik timeout
  reverse-proxy.md
Labels: 3. to review, documentation

#6869 aio-interface: to allow to install the latest hub version
  php/src/Controller/DockerController.php
  php/templates/containers.twig
Labels: 3. to review, enhancement

#6894 add recommendation to use orbstack on macOS
  readme.md
Labels: 3. to review, documentation

#6900 nextcloud-entrypoint: allow to configure av_blocklisted_directories
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#6913 talk: update eturnal image tag to use alpine image
  Containers/talk/Dockerfile
Labels: 3. to review, dependencies

#6903 fix: unify default initialization of s3 `autocreate`, `use_ssl`, `use_path_style` and `legacy_auth`
  Containers/nextcloud/config/s3.config.php
Labels: 3. to review, bug
