Repository nextcloud/all-in-one, pull requests merged in 2025-03, with the labels that each got.

#6129 helm-chart: add docs that ingress is not built-in
  nextcloud-aio-helm-chart/readme.md
Labels: 3. to review, documentation

#6094 clamav: build the container also for aarch64/arm64 by using the alpine package
  Containers/clamav/Dockerfile
  Containers/clamav/clamav.conf
  Containers/clamav/healthcheck.sh
  Containers/clamav/start.script
  Containers/clamav/start.sh
  Containers/clamav/supervisord.conf
  Containers/whiteboard/Dockerfile
  manual-install/readme.md
  manual-install/update-yaml.sh
  php/containers.json
  php/public/index.php
  php/src/Data/ConfigurationManager.php
  php/templates/includes/optional-containers.twig
  readme.md
Labels: 3. to review, enhancement

#6108 Hide password by default
  php/templates/components/container-state.twig
  php/templates/containers.twig
Labels: 3. to review, enhancement

#6135 Revert "build(deps): bump collabora/code from 24.04.12.4.1 to 24.04.13.1.1 in /Containers/collabora"
  Containers/collabora/Dockerfile
Labels: 3. to review, dependencies

#6141 rp-docs: add workaround to NPMplus reverse proxy example
  reverse-proxy.md
Labels: 3. to review, documentation

#6162 community-containers: add smb-server
  community-containers/smbserver/readme.md
  community-containers/smbserver/smbserver.json
Labels: 3. to review, enhancement

#6134 Add support for ghcr.io
  community-containers/helloworld/helloworld.json
  community-containers/helloworld/readme.md
  php/containers-schema.json
  php/src/DependencyInjection.php
  php/src/Docker/DockerActionManager.php
  php/src/Docker/GitHubContainerRegistryManager.php
Labels: 3. to review, enhancement

#6157 Update docjyJ's community container images
  community-containers/nocodb/nocodb.json
  community-containers/nocodb/readme.md
  community-containers/stalwart/stalwart.json
Labels: 3. to review, enhancement, blocked

#6165 update Nextcloud to 30.0.7
  Containers/nextcloud/Dockerfile
Labels: 3. to review, dependencies

#6181 update Github Actions to use commit hashes for 3rd party actions instead of version tags
  .github/workflows/codespell.yml
  .github/workflows/dependency-updates.yml
  .github/workflows/helm-release.yml
  .github/workflows/imaginary-update.yml
  .github/workflows/lint-helm.yml
  .github/workflows/lock-threads.yml
  .github/workflows/nextcloud-update.yml
  .github/workflows/php-deprecation-detector.yml
  .github/workflows/psalm-update-baseline.yml
  .github/workflows/shellcheck.yml
  .github/workflows/talk.yml
  .github/workflows/twig-lint.yml
  .github/workflows/update-helm.yml
  .github/workflows/update-yaml.yml
Labels: 3. to review, dependencies

#6190 test: prepare for e2e tests
  php/src/Data/ConfigurationManager.php
  php/templates/containers.twig
  php/templates/setup.twig
Labels: 3. to review, enhancement

#6167 Change stalwart tag
  community-containers/stalwart/stalwart.json
Labels: 3. to review, enhancement

#6189 aio-interface: add e2e tests via playwright
  .github/workflows/playwright.yml
  Containers/mastercontainer/Dockerfile
  php/tests/.gitignore
  php/tests/package-lock.json
  php/tests/package.json
  php/tests/playwright.config.js
  php/tests/tests/initial-setup.spec.js
  php/tests/tests/restore-instance.spec.js
Labels: 3. to review, enhancement

#6178 nextcloud-entrypoint: output error message if touch failed
  Containers/nextcloud/entrypoint.sh
Labels: 3. to review, enhancement

#6217 move images to ghcr.io
  .github/workflows/playwright.yml
  .github/workflows/update-helm.yml
  Containers/mastercontainer/start.sh
  develop.md
  php/containers.json
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#6200 helm: allow to set the skeleton directory
  Containers/nextcloud/entrypoint.sh
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, enhancement

#6205 docker-socket-proxy: more strict rules for the container creation
  Containers/docker-socket-proxy/haproxy.cfg
Labels: 4. to release, enhancement

#6218 docs: nextcloud/all-in-one moved to ghcr.io
  community-containers/readme.md
  compose.yaml
  manual-upgrade.md
  multiple-instances.md
  php/README.md
  readme.md
  reverse-proxy.md
Labels: 3. to review, enhancement

#6222 aio-interface: rename `isDockerHubReachable` to `isRegistryReachable`
  php/src/Controller/DockerController.php
  php/src/Docker/DockerActionManager.php
Labels: 3. to review, enhancement

#6235 link to borg logs while borg is running
  php/templates/containers.twig
Labels: 4. to release, enhancement

#6231 clamav: use correct clamd.conf in freshclam
  Containers/clamav/supervisord.conf
Labels: 4. to release, bug

#6243 borg: exclude lost+found directory from backup
  Containers/borgbackup/backupscript.sh
Labels: 3. to review, enhancement

#6236 helm-chart: move alpine init-container image to containers folder
  Containers/alpine/Dockerfile
  nextcloud-aio-helm-chart/update-helm.sh
Labels: 3. to review, enhancement

#6223 move szaimens community containers to ghcr.io
  community-containers/borgbackup-viewer/borgbackup-viewer.json
  community-containers/caddy/caddy.json
  community-containers/fail2ban/fail2ban.json
  community-containers/libretranslate/libretranslate.json
  community-containers/local-ai/local-ai.json
  community-containers/scrutiny/scrutiny.json
  community-containers/smbserver/smbserver.json
  community-containers/vaultwarden/vaultwarden.json
Labels: 3. to review, enhancement

#6232 watchtower: install from github repo to fix some security issues
  Containers/imaginary/Dockerfile
  Containers/talk/Dockerfile
  Containers/watchtower/Dockerfile
Labels: 3. to review, enhancement

#6250 collabora: fix permissions for /etc/coolwsd/coolwsd.xml file
  Containers/collabora/Dockerfile
Labels: 3. to review, enhancement

#6251 collabora: fix permissions correctly
  Containers/collabora/Dockerfile
Labels: 3. to review, enhancement
